### ISSUE TITLE
Using extra thumbs mode, the thumbs show but not any plot or info show

### ISSUE THREAD

**Issue by pix** [pix/aeon#1]
No movie info in the middle of the screen:
http://a.imageshack.us/img375/6120/thumbview.jpg

<del>Strange shadow in the upper left corner</del> Fixed in e45d3b49492535715784517ac88e0e0975eebf9f

**Comment by chanders** [comment]
Same thing here. Also this view should alert the viewer that no extra thumbs are available to show if they don't exist, instead of putting up blank frames.

**Comment by mindweaver** [comment]
Sadly it is not possible to check wether a file exists or not :/ There is no support for that in XBMC.

**Comment by pix** [comment]
Damn this view is _seriously_ broken

**Comment by pix** [comment]
Maybe we can put a fallback texture ?

**Comment by pix** [comment]
Closed by bf7639c3cd76c1a64d724312c21f50f3778adf03: Using extra thumbs mode, the thumbs show but not any plot or info show (HOORAY !)

The generic panel in the middle is shared between all the OldMultiplex
Multiplex and Showcase view. Bugs are expected with this commit. Please
reports them
