### ISSUE TITLE
Poster not correct in lowlist for TV Shows

### ISSUE THREAD

**Issue by chanders** [pix/aeon#100]
As the subject said..

**Comment by pix** [comment]
Any more details ? Screenshots ?

**Comment by chanders** [comment]
Well there is not much to explain really. When viewing tv shows in low list, the posters (or banners) does not correspond to the respective show. Even if you remove the poster and add it back. 

It works well in other views however.

**Comment by pix** [comment]
Work fine for me :/ This is why I asked for a screenshot :/

**Comment by chanders** [comment]
Here you go :)

<img src="http://uppix.net/7/1/1/e9c3b529f375f02cc3757c3c0b553.png"></img>

<img src="http://uppix.net/1/1/0/8767b52188df1113154a8b9255333.png"></img>

**Comment by pix** [comment]
It definitly works fine for me :/ 

Have you tried with an older/newer version of aeon ?

**Comment by chanders** [comment]
Unfortunately the only version of Aeon I have is this one..

**Comment by pix** [comment]
Of xbmc sorry :/

**Comment by chanders** [comment]
This can be closed. I removed the offending shows and did a rescan. All seems to be working now.
