### ISSUE TITLE
Watched overlay incorrectly positioned for Multiwall

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#101]
## Relevant Settings:

TV Library View: Multiwall
Aeon Viewtype Options / Use TV Posters for Multiwall (Enabled)

**Comment by pix** [comment]
Closed by 6736682ebd5a458a0214e9729b19f7e68e91a451: Watched overlay incorrectly positioned for Multiplex TV Posters

**Comment by sialivi** [comment]
Much better, but not perfect. There's still a gap on the right edge, most easily seen with a white poster.

**Comment by pix** [comment]
Watched overlay in Multiplex and Multiwall

Closed by 0de273fb5bcaae6717433ce7a9ef452e18285fc0: Improvements for Watched overlay with Multiwall TV Posters
Closed by 0de273fb5bcaae6717433ce7a9ef452e18285fc0: Watched overlay incorrectly positioned for Multiplex

**Comment by pix** [comment]
> There's still a gap on the right edge

I'm afraid, i'm not sure if I can do better by tweaking the offsets.
