### ISSUE TITLE
Improvements for Watched overlay with Multiwall TV Posters

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#102]
## Relevant Settings:

TV Library View: Multiwall
Aeon Viewtype Options / Use TV Posters for Multiplex/Multiwall (Enabled)
## Problem:

1) The watched overlay are very badly positioned
2) The watched overlay used here doesn't seem very suitable for this view. The overlay used in Multiplex would look much better.

**Comment by pix** [comment]
Watched overlay in Multiplex and Multiwall

Closed by 0de273fb5bcaae6717433ce7a9ef452e18285fc0: Improvements for Watched overlay with Multiwall TV Posters
Closed by 0de273fb5bcaae6717433ce7a9ef452e18285fc0: Watched overlay incorrectly positioned for Multiplex
