### ISSUE TITLE
Aspect ratio "scale" not "strech" in Artist Thumbnails, Music Multiplex

### ISSUE THREAD

**Issue by ghost** [pix/aeon#103]
I have been trying to fix this myself but nothing seems to happen when i ad the correct strings. Im sure you guys can fix it.

When this is done the music multiplex will be complete and look amazing!

This is the problem:
http://img823.imageshack.us/img823/5582/screenshot000o.png

They should just scale and keep their aspect ratios, will look much better.

**Comment by pix** [comment]
Closed by 9d66ed052698302f69b1bed43a79d41c999abdc0: Aspect ratio "scale" not "strech" in Artist Thumbnails, Music Multiplex
