### ISSUE TITLE
Info Dialog Showing DD 2.0 even though no streams of that type

### ISSUE THREAD

**Issue by mark007** [pix/aeon#104]
Hi,

I have some old movies (and 1 or two new ones) stored in real-video/ real-audio formats.

The nfo file contains video codec "rv40", and audio codec "cook". Although aeon65 doesn't recognize these, in the info dialog aeon65 still shows an audio flag of Dolby Digital 2.0....

I have very quickly created a cook.png and rv40.png file and placed them in the audio and video codec folders of the aeon skin. These show up perfectly but again, in the info section, I see a Dolby Digital 2.0 sticker incorrectly. See images.

My feature request is that rv30.png and rv40.png be given images for in the video codec folder, perhaps an improved version of what I attach below... aswell as a cook.png image to support the real "cook" audio codec..

My bug report is that dolby digital 2.0 shows up incorrectly in this case..

See here, the new video and audio codec images I quickly created in photoshop show up perfectly.
http://img831.imageshack.us/i/screenshot014a.jpg/

But here, the info dialog says dolby digital 2.0 http://img178.imageshack.us/i/screenshot015m.jpg/

Here is the rough png I put together for rv40.png, rv30.png and cook.png. I'm happy with it for the time being personally..
http://img827.imageshack.us/img827/2194/cook.png

**Comment by pix** [comment]
Working on it...

**Comment by pix** [comment]
I started a branch to do some refactoring on audio media flag. Can you test this http://github.com/pix/aeon/archives/audiogenerator And (cook should be displayed, I just need some feedback to see if its works on another machine than mine :))

**Comment by mark007** [comment]
Downloaded new branch and looks great for cook audio :) Thanks.

**Comment by pix** [comment]
This has benn maerged back into master now, Into the wild for testing... :-)
