### ISSUE TITLE
Korean strings.xml

### ISSUE THREAD

**Issue by epoke** [pix/aeon#105]
Korean langage file.
Download link here ->
http://xbmc-korea.com/xe/?module=file&act=procFileDownload&file_srl=26293&sid=0a206a6cf6fefc514b825ee452e7afbe

**Comment by pix** [comment]
Translations: Added Korean strings

Closed by 8fa89b1e9770fc0ae9c5257ff5087b3c63ca1f00: Thanks to epoke
