### ISSUE TITLE
TV Show Fanart disappears after watched

### ISSUE THREAD

**Issue by geseib** [pix/aeon#106]
Only happens on current show. other episodes are fine. Will restore if you go out to main menu and return back to the episode list.

Tested with other skins (night, confluence), no problem.

**Comment by geseib** [comment]
ok, confluence has the problem with movies, but not with tv shows.

**Comment by alastor2262** [comment]
seems ok now for tv show but still got the problem on movies with :
pix-aeon-0.0.1-199-gfdb4134
only when iam using an external player (mpchc)

**Comment by geseib** [comment]
Agreed. TV shows now seems ok, but movies still has the problem. What was changed to fix?

**Comment by phil65** [comment]
workin here. if it still occurs it´s probably an xbmc bug
