### ISSUE TITLE
Error in views under programs, etc Launcher plugin

### ISSUE THREAD

**Issue by ghost** [pix/aeon#107]
Ive noticed for quite some time that the views under "Games" or Programs have some bugs.

This is the only major bug left in this skin in my opinion.

In this view the wall arrows are visibly even though its the list view and the name at the bottom is unnecessary. This view should be like the list view under every other media like Movie and Music.

http://img834.imageshack.us/i/screenshot001i.png/

In the showcase view it's the same problem, the wall arrows are visible.

http://img689.imageshack.us/i/screenshot002me.png/

And in the wall view it's really messy. It should be the 2:3 aspect ratio like in showcase and not the 1:1 as in music. Also as you can see, the images are not displaying correctly.

http://img827.imageshack.us/i/screenshot003c.png/

Hope you fix this view and make it just as thought-through as the rest of the skin :)

**Comment by temmi2000** [comment]
never used that area, that´s why I never looked into it.
I have to see whether I fix the bugs or simply deactivate some viewtypes in that area for now.

**Comment by temmi2000** [comment]
made some quick changes to wall view, bugs are fixed now?

**Comment by ghost** [comment]
Yes, the view is completely fixed, AWESOME! :D you can close this now :)

**Comment by phil65** [comment]
perfect :)
