### ISSUE TITLE
Unfortunate sideeffect of the new default images during fade in/out

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#110]
An unfortunate sideeffect of the new default images is that they are very noticeable when certain viewtypes fade in/out. Multiplex, Wall, Multiwall and others are effected. When entering or exiting the movie library the movie cover images fade in/out and behind them the new default images are very clearly seen. This is rather ugly. Some of the viewtypes, like Old Multiplex, doesn't have this problem.

**Comment by pix** [comment]
It should be ok now, Reopen this issue if some images are stil broken

**Comment by sialivi** [comment]
Maybe my explaination of the issue wasn't making sense, but whatever fix you're refering to did nothing for this issue. How do I reopen an issue?

**Comment by pix** [comment]
My bad I misread the issue, anyway this issue is reoppened.

**Comment by sialivi** [comment]
Here's a screenshot of the Multiplex fade in/out I'm talking about, those default images makes the transition really ugly:

http://img444.imageshack.us/img444/7797/multiplex.jpg

**Comment by pix** [comment]
Closed by 9e2370505f212052bcb7225e12ae88ad4dbf7682: Unfortunate sideeffect of the new default images during fade in/out
