### ISSUE TITLE
Clearart fallback to logo in dialogseekbar xml

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#111]
Nice work on the new seekbar! You might consider a follback for clearart.png (when N/A) to logo.png, as suggested here http://forum.xbmc.org/showpost.php?p=592331&postcount=32
I tried it, but i can't make it work

**Comment by pix** [comment]
It's not possible for now. There's no way to tel if a texture exists or not. You should post a XBMC feature request in order to do this.
