### ISSUE TITLE
Piano image while video is playing?

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#115]
By design or a mistake? I'm not sure a piano makes much sense as the default image for a video that is playing:

http://img121.imageshack.us/img121/2716/pianoec.jpg

**Comment by sialivi** [comment]
Looks like this has been fixed. However, it does look a bit odd now that the spinning CD isn't centered vertically now that the image is in another aspect ratio.

**Comment by phil65** [comment]
should be fixed now
