### ISSUE TITLE
Changing watched image

### ISSUE THREAD

**Issue by phil65** [pix/aeon#116]
what do you think about changing all watched images to the small blue glowing check mark?
would also remove the need to position them pixel-perfect, which is really annoying when you´re coding in front of a 16:10 monitor.

**Comment by sergiocos** [comment]
that's ok for me! and the check mark is language independent, one more reason to do it.

**Comment by sialivi** [comment]
I really liked the diagonal bands, but I can live with that change

**Comment by phil65** [comment]
hmm only change it in wall views?
or can somebody be so nice and positon them all correctly again?` :)

**Comment by pix** [comment]
I want to keep it, the new checkmark while ok for lowlist isn't too great ihmo for showcase wall etc...

Instead of displaying an image we could display text then rotate it to 45° (This maybe a little hard but it would be translatable)

**Comment by mindweaver** [comment]
I do not want to go back to the blu glowing checkmark. It is hard to see on most covers and does not fell as nice as the diagonal band.

**Comment by phil65** [comment]
ok, then we´ll keep it, but one of you guys has to do the positioning for the wall views ;)
concerning localization: there´s also a boolean condition to check the system language I think, that could also be a solution.

**Comment by Bat3man** [comment]
if you guys can point me to the line in the xml where the positioning is done, I can fiddle around with it to make it fit if you guys want.

**Comment by phil65** [comment]
open viewtype_wall.xml / viewtype_fullscreenwall.xml and search for listitem.overlay, you should find some image controls which have to be adjusted.

**Comment by Bat3man** [comment]
Allright. That's Fixed. Now if you can point me in the right direction for the darkoverlay in normal grid (not working) and removing the fanart background, then it's done.

**Comment by pix** [comment]
phil could you take a look at 8b9bb6b970a8a98f3c2b3c5f6e564ace351d3cb4 what do you think of that ?

**Comment by Bat3man** [comment]
Wow Pix that's Cool. Did you change the placement of the overlay as well? I just wanted to Pm Phil with the correct placement for 16:9.

**Comment by phil65** [comment]
closed
