### ISSUE TITLE
Add trailers to popup when selecting movie

### ISSUE THREAD

**Issue by Bat3man** [pix/aeon#118]
New versions of XBMC have the ability to, when pressing enter on a movie or tvshow, have a popup to choose the action you want: play, or more information. It would be cool to have the ability to start the trailer from that menu as well. Maybe even the Theater Experience script as well.

This is a feature suggestion.

**Comment by phil65** [comment]
not possible on skinning level, the list is automatically filled by xbmc.

**Comment by Bat3man** [comment]
That's What I was afraid of. Will close, maybe i'll ask it sometime in the xbmc dev subforum
