### ISSUE TITLE
Implement the Randomitems script

### ISSUE THREAD

**Issue by Bat3man** [pix/aeon#119]
I would love to see the randomitems script created by Hitcher and Nuka implemented in Aeon.
I think, but that's just personal that it can be implemented on the place the "latest additions" widget is. When you stay on "movies", for the first 4 or so seconds the "latest additions' is visible, it slides out of the screen,  and then the randomitems "featured" slides in the screen. Then after 4 seconds this slides out again and the "latest additions" slides in again.

Link to forum item for script:
http://forum.xbmc.org/showthread.php?t=79378&highlight=featured+script

**Comment by phil65** [comment]
I doubt  that this is possible the way you want it, but it would be possible to add an option to choose betwee those two lists (or to show both)

**Comment by Bat3man** [comment]
Cool! Only if you are into it of course.

**Comment by phil65** [comment]
done in font_rework
