### ISSUE TITLE
Make "director" in movie view selectable like the actors.

### ISSUE THREAD

**Issue by Bat3man** [pix/aeon#120]
An Idea I was having for a while now: I use the show cast quite a lot, especially to see what other movies the actor played in. I would love that same funcionality for directors. So that the director is clickable, and you get a list of all the other movies in your library that guy has made.
I would be even cooler if you could see a list of ALL the movies that director has made, (kinda like a discography for artist) and it would be visible which movies are IN your library, and which ones you are missing. But that is something XBMC cannot do by itself. But it would be cool. ;-)

**Comment by phil65** [comment]
you should ask a script coder for that, not possible on skinning level.

**Comment by Bat3man** [comment]
will do.
