### ISSUE TITLE
With Kiosk Mode on, the Trailer button is not visible in videoinfo screen.

### ISSUE THREAD

**Issue by Bat3man** [pix/aeon#121]
The new Kiosk mode has a small error. You put the trailers buttons in the kiosk mode. So with Kiosk mode on, the trailers button in the info screen is not visible. 

Line 271:
<visible>!Skin.HasSetting(kioskmode) + Container.Content(movies) + Skin.HasSetting(youtrailer)</visible>

**Comment by phil65** [comment]
didn´t i fix that some days ago??

**Comment by Bat3man** [comment]
did you...  You did.... I'm sorry. Didn't Check man.

**Comment by pix** [comment]
So, fixed or not ?

**Comment by phil65** [comment]
fixed
