### ISSUE TITLE
Curtain setting

### ISSUE THREAD

**Issue by phil65** [pix/aeon#125]
may I remove the curtain settings?
we could use a togglebutton with fanart on/off instead, that should be enough..

**Comment by pix** [comment]
You could. I never used it so...

**Comment by phil65** [comment]
hmm or we delete that option completely... I think everyone who uses aeon uses fanart...the option for a fallbackimage is sufficient I think.

**Comment by Bat3man** [comment]
Agreed. Remove it.

**Comment by phil65** [comment]
removed. -->closed
