### ISSUE TITLE
new Fullscreen Wall: remove fanart/backgrounds

### ISSUE THREAD

**Issue by Bat3man** [pix/aeon#127]
In the new full screen wall the background fanarts are seeping trough the posters. With fanart I mean the normal fanart by movie and the home menu scrolling fanart. This is not looking great. I think the fullscreen does not need fanarts. Also for speed purposes: the smoe trails can be removed from this view. You don't see any of it.

PS: The black overlay is not working for the normal grid size. It's allways on.

**Comment by phil65** [comment]
fixed
