### ISSUE TITLE
Missing Info Panel animation when entering Movies Multiplex

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#128]
## Settings:

View: Multiplex
Show Info Panel: Auto
## Steps:

1) Enter Movies
2) Don't touch anything.. wait for the Info Panel to show up
Result: The Info Panel just appears instead of sliding in from the top of the screen like it should
3) Navigate to another movie
4) Wait for the Info Panel to show up
Result: The Info Panel slides down from the top of the screen as it should.

**Comment by phil65** [comment]
fixed
