### ISSUE TITLE
"Recently Added" action for Music

### ISSUE THREAD

**Issue by CaptInsano** [pix/aeon#129]
When an album is selected from the "Recently Added" widget for music,only the first song of the album is played. 

The more logical action to tie in with the the other Recently Added Widgets would be to play the entire album, seeing as the Album Name not the Song Name appears.

**Comment by phil65** [comment]
not in our hands (unless pix is able to code in python :))

**Comment by pix** [comment]
Reoppened, I'll see what I'll could do.
