### ISSUE TITLE
Some labels in OSD menus are not aligned properly

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#13]
- Audio & Video Menu

**Comment by mindweaver** [comment]
The weird thing is that they were aligned before. Something must have changed in XBMC. I have posted about this on the skinning forum. 

http://forum.xbmc.org/showthread.php?t=76734

**Comment by pix** [comment]
Can this issue be closed ?

**Comment by mindweaver** [comment]
No it's still an issue. So let's leave it open. maybe we can do something to force it to align.

**Comment by mindweaver** [comment]
Fixed!
