### ISSUE TITLE
Fallback Fanart not working in File mode

### ISSUE THREAD

**Issue by chippie** [pix/aeon#131]
Not sure when it started but Fallback FanArt no longer works when in file mode. For movies with missing fanart it shows whatever backdrop has been selected for the "Video" Main Menu Item under Settings/Main Menu/BackDrops.

**Comment by phil65** [comment]
was never included till now, will be done when I find some time.

**Comment by chippie** [comment]
Hi, note sure if you remember but I requested the fallback fanart a long time ago and you obliged... Have to add though that it DID work in File mode, as I mostly go in to "Videos" due to the way my folders are organised and I definately used to get a black screen where there was no fanart and this was irrespective of what the Video Main Menu Item background was set to. I only noticed the change a few days ago, perhaps from when you made some fallback fanart changes.

**Comment by phil65** [comment]
then show me where :)
http://github.com/pix/aeon/commits/master/720p/MyVideo.xml
i´m pretty sure it was never there. otherwise I must have been drunk.

**Comment by chippie** [comment]
Not saying if it was a code change you made, sorry if it came across like that, I was just asking the question. Could it be related to a change in the XBMC builds themselves that has caused this? Perhaps I am not explaining the problem correctly. I use the UserData Thumbs/Fanart folder as my backdrop folder for both Movies and Video on the Home screen, whenever my kids access their movies it is always under Video, where I navigate to their Kids folder. Previously they had blank backgrounds where their movie did not have fanart now they have random fanart from any movie in my collection including horrors. Believe me this has only just started to happen recently, I am very careful as t what my kids can see. At the same time I noticed that browsing folders under the Video menu also displayed my random fanart, I never saw this before also.

**Comment by chippie** [comment]
Philipp, Sorry I owe you an apology,
For some reason I actually forgot that a friend of mine made that change for me soon after you added the fallback fanart option for me and then you became involved in your studies. My only excuse is I have had a heavy week and just forgot. Anyway, I have lost the code he added so when you have time please could add the fallback fanart feature to Videos (File Mode).
If possible could you see if you can work it so that when you focus on a folder it will still displays the fanart or random fanart as set under Main Menu Backdrops (unless there is fanart associated with that folder) but when focused on a movie it displays the fallback fanart. This last part is a nice to have and not essential if at all possible.

Again, sorry for any confusion. Thanks.

**Comment by phil65** [comment]
Fallback for files added. Closed.

**Comment by chippie** [comment]
Hi, thanks for doing this, however cannot seem to get the fallback to work, do not have an option fro Video Mode and when browsing in Video mode still seem to get the same fanart that is set for VIDEO on the home page. Any pointers appreciated. Thanks.
