### ISSUE TITLE
Glow around tv show episode not the same shape

### ISSUE THREAD

**Issue by mark007** [pix/aeon#135]
Hi,

Again not a big issue just a slight cosmetic issue. When viewing tv show episodes, I notice the lovely blue glow around each episode doesn't seem to match up in size with the background image, see highlighted area in screenshot.

http://img291.imageshack.us/img291/250/screenshot060i.jpg

Its just as if the two sizes of curvature arn't the same leading to a slight cosmetic problem.

**Comment by phil65** [comment]
should be fixed now

**Comment by mark007** [comment]
Sweet thanks as always.
