### ISSUE TITLE
Science Fiction Genre

### ISSUE THREAD

**Issue by mark007** [pix/aeon#136]
Hi,

I noticed today looking through some of my movie genres that I have some movies that are in genre sci-fi and some in genre Science Fiction. Can an image be added for this genre as I assume its not under aeon control to combine both into one visual genre.

http://img231.imageshack.us/img231/5655/screenshot061n.jpg

**Comment by ghost** [comment]
You can either use Ember Media Manager to change all to either Sci-Fi or Science Fiction, thats what I did. Or you can do it the quick way and just copy your sci-fi icon under extras/moviegenre and name it "science fiction.jpg". This will show the same icon as for sci-fi.

**Comment by mark007** [comment]
Yeah I created the duplicate image (actually had an invalid image already there for "Science Fiction.png", so not sure if that invalid image is there on github.

Is there a way we could check what genres might be the most common and check them against the ones aeon65 has a genre image for. I'm sure most of the top ones are already catered for I just know alot of others will have the same issue with sci-fi versus science fiction.

**Comment by phil65** [comment]
there isn´t  a real nice way to do check that., I think we should only support the genre names picked up by the tmdb server, if you want different names supported you have to rename the jpgs. Closed.
