### ISSUE TITLE
Some minor flaws that has appeard lately

### ISSUE THREAD

**Issue by ghost** [pix/aeon#137]
I have noticed some things that have appeared lately and has worked before.

Fanart isn't working under Music pages, only when the artist actually have a fanart it appears, before it showed some random fanart when you selected between artist, albums etc. It can't be by design?
http://img26.imageshack.us/i/screenshot001kr.png/

<del>Also under TV Shows you could have a poster.jpg in the folder that showed in the Fullscreen Info page, otherwise the landscape logo fpr the show get stretched and looks awful. I think i read this somewhere that you removed it, I can't for the love of my life understand why. Don't wake the skin worse!
http://img823.imageshack.us/i/screenshot002j.png/
</del>

<del>And last, when you press right under episodes in Low List view the thumb is stretched, before it was just scaled and it looked much better.  http://img816.imageshack.us/i/screenshot003o.png/</del>

Sorry to be nagging you guys but I really think that you shouldn't keep changing settings that doesn't make a problem, there's probably a reason why they exist in the first place.

**Comment by pix** [comment]
> I really think that you shouldn't keep changing settings that doesn't make a problem

I love this kind of comments seriously I do. Think you can do better ? Then no problems, there's a fork button on github. We're not breaking stuff for fun, there's usually a reason why we're changing things. Bugs happen.

> Also under TV Shows you could have a poster.jpg

Just use the "Set Thumb" button and set a poster for the TV Show

> <del>And last, when you press right under episodes in Low List view the thumb is 
> stretched, 
> I'll fix this...</del>**Fixed**

**Comment by ghost** [comment]
I really don't want to sound rude, I guess I don't do well in text. I know that you guys do this on your spare time and thats just great. I think I will be quiet about this now cause I obviously don't know what I'm talking about, I just get the picture that I don't see anything else happening with the skin except that more things that worked before stop working. But I don't really know how all the code affect other code and I guess bugs happen as you say. Just ignore me if I make any more statements about things i don't know.

About the poster.jpg stuff I meant that when you pressed the "i" button and brought up the info screen on a TV Show the icon on the left reverted to the poster.jpg in the same folder. It could actually be a totally different image than the one shown in landscape view, allowing you to have a image adjusted for landscape view as your TV Thumb and a image adjusted for the 3:2 aspect ratio displayed under info dialog to match the aspect there. This was added 1 month ago maybe and I really liked it but now it don't seem to work anymore.

Thx for fixing the aspect on the lowlist btw :)

**Comment by pix** [comment]
Thanks for the studio icons :-)

**Comment by pix** [comment]
> Also under TV Shows you could have a poster.jpg

This should be fixed, poster.jpg has been readded, and cleaned up so no more superposition of transparent posters. folder.jpg support has been added to for views that shows 2:3 thumbs (Disabled by default)

**Comment by phil65** [comment]
about music fanart: it should work, you have the fallback image option activated?
I made a seperate now for music.

**Comment by ghost** [comment]
Yeah, my bad. Really sorry about that. I had fallback activated for videos but i left the field blanc for music, should have realized that :)

**Comment by phil65** [comment]
can be closed now I think
