### ISSUE TITLE
VideoPlayer.Date not working in dialogseekbar.xml

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#139]
VideoPlayer.Date seems not to work for me in dialogseekbar.xml :(

**Comment by sergiocos** [comment]
but i can confirm, as stated in forum, that in newer builds of xbmc that .premiered works now as it should. However, Listitem.Date looks better for me in LowList, because now it's used the regional date system, not the american (scraped) date of air. Maybe, if others can confirm that Videoplayer.Date don't work in dialogseekbar, you should revert it to .premiered

**Comment by phil65** [comment]
reverted that, thx
