### ISSUE TITLE
No MUSIC in main menu

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#140]
It's toggled ON in Settings, but no joy. I didn't have the time to add files to music library after a clean install (XBMCSetup-Rev33619-dx) and now there's no shortcut for music. Might be a bug in this build (can't remember if it was present 2 days ago and it's gone after recent modifications in Aeon65). Long story short: the shortcut for music works as it should for you?
P.S.: Also MUSIC VIDS shortcut cannot be toggled ON, it's only 'grey' in settings, so it might be only an xbmc issue. I've spent a lot of time to configure the dsplayer build to try another, so maybe you can reproduce this so I know who's to blame. Thanks!

**Comment by sergiocos** [comment]
After removing ' + Library.HasContent(Music)' from Includes_MainMenu, now I have MUSIC, so it's a skin issue: no MUSIC in main menu if no library.

**Comment by phil65** [comment]
will be fixed, didn´t think long enough about that change.

**Comment by phil65** [comment]
should be fixed now
