### ISSUE TITLE
Entering music in low list shows nothing until you press up or down

### ISSUE THREAD

**Issue by kraaa** [pix/aeon#142]
Using low list viewmode and entering music, does not show any menu's until you press down or up.

**Comment by phil65** [comment]
cannot replicate that. screenshot?

**Comment by kraaa** [comment]
now i know what it is. its the autoinfo that bugs out when its taking too long time. Cant you make a setting so that it starts after going to left or right?

**Comment by phil65** [comment]
fixed in font_rework
