### ISSUE TITLE
Pressing i on movie showing path/filename

### ISSUE THREAD

**Issue by kraaa** [pix/aeon#143]
I want to be able to see the path/filename for the movie/episode i got marked.
The reason is that i want to be able to see if xbmc scanned it correctly or not.

**Comment by sialivi** [comment]
No thanks, there are surely better ways to do that than adding clutter to the skin?

**Comment by kraaa** [comment]
Well it could maybe be added as an option...

**Comment by phil65** [comment]
added, closed
