### ISSUE TITLE
Title overlap in LowList

### ISSUE THREAD

**Issue by ghost** [pix/aeon#144]
I've noticed that if the title of an episode is to log, it will overlap the flags at the right under detail view in LowList.

http://img163.imageshack.us/img163/3464/screenshot005me.png

I think it would be nicer to either lower the font 1, 2 notches or move the title under the Poster to the right. Maybe lowering the font is nicer though because a lot of titles get cut down because of its length.

**Comment by pix** [comment]
Closed by 56c9f014b96934cd00847dbfd682950e5342a1ea: Title overlap in LowList
