### ISSUE TITLE
Info Dialog - No Plot revert to Plot Outline

### ISSUE THREAD

**Issue by mark007** [pix/aeon#145]
Hi, I had a similar request for this a while back but I have some movies that have a plot outline and no plot.

In the info dialog can the plot outline also be shown as a fallback to the plot if the plot is empty?

**Comment by pix** [comment]
Closed by 5508cfff79512312680620abfcfde2a8762ebb4d: Info Dialog - No Plot revert to Plot Outline

Yes it can !
