### ISSUE TITLE
Info / Seek Bar enhancement

### ISSUE THREAD

**Issue by ghost** [pix/aeon#147]
This is an enhancement to the seek bar and info view under videos.

This is how I think it should look. With the top of the old info but the bottom of the new one untouched (two lines for info and just one for the seekbar).
http://img40.imageshack.us/img40/5185/namnlst1x.jpg

The seek bar should look like it does now except that you only see the episode number like the bottom of my picture.

The movie info could be untouched because I think it looks awesome (you guys did a really good job on that one). But i think the seek bar can have only one line of info at the bottom like in TV shows (genres).

The seek bar should be like it is now except it only show genres at the bottom and not two lines of information like it is now, that can be as it is in info view though as I said earlier.

Sorry for all the "should" words but I'm not that versatile in expressing myself in English. Hope you get what I mean and do you think it's a good improvement?

**Comment by pix** [comment]
And for movies? The year is in the already shown at the bottom, so In order to remain consistent, and also have a bar on top what can we display an idea ?

**Comment by phil65** [comment]
perhaps adding the tagline (or plot) and mediaflags to the top?

**Comment by ghost** [comment]
Yeah I thought of this and maybe it isn't such a good idea to readd the top thing. I just miss the year on tv shows and a title when the show don't have a clearart.

I think it would be nice if the episodeimage would be removed and the year/rating would be shown in the same way as in movies, but on the right side. I don't think you need a snapshot of the episode you are watching.

Is it also possible to add the title in text to the left side when a clearart don't exist?

**Comment by sergiocos** [comment]
there's a fallback for logo.png when clearart don't exist. and logos are for almost every show: http://www.lockstockmods.net/clearart/

When there's no clearart, there's a logo, and i think it looks very good ;)
http://img20.imageshack.us/img20/6683/screenshot000g.png

**Comment by ghost** [comment]
Yeah ok, forget the title then. An improvement would be just to add year and rating on the right instead of episode image I think. Also to make things consistent I think the poster on the right in movie should be moved to the left and year/rating to the right, it makes more sense for the poster to be on the left, don't know why :P

**Comment by phil65** [comment]
closed, reworked in Aeon65 v2.0
