### ISSUE TITLE
[REQUEST] Shift fanart in poster view

### ISSUE THREAD

**Issue by chanders** [pix/aeon#149]
When in poster view (view with posters disappearing into the distance) the fan art is blocked by all the posters. By shifting the fanart up a little, the center of the fanart is now viewable over the posters.

**Comment by phil65** [comment]
i think that´s not very useful, a lot of heads in fanart won´t be visible then.

**Comment by chanders** [comment]
Only shifting it by 100px would make the world of difference. And I am sure a lot of heads wouldnt be cut off.

**Comment by phil65** [comment]
i will shift the posters to the bottom and remove the mediaflags and the floorlabels for that view, is that ok? will make an infopanel (probably like in multiwall) then

**Comment by chanders** [comment]
actually phil, the view is perfect except for th fanart not being shown, hence my suggestion to just shift it up a little so the focal point of the art is visible. If it cant be dont I would suggest leaving the view as is as the media flags do come in handy !

**Comment by phil65** [comment]
hmm I don´t really like it the way it is now... it´s irritating that the focused movie is on the left, but the movie title is in the center. will change that I think.

**Comment by phil65** [comment]
thaught about it again, fanart shift for poster view will be optional in Aeon 2.0
