### ISSUE TITLE
ExtraFanart support

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#150]
Feature Request:
Some xbmc skins support cycling through multiple fanart images for a single movie when being stored in a subfolder called ExtraFanart

**Comment by phil65** [comment]
hmm i just tried that, but it doesn´t look good because it takes some time to show up and you can see the fanart of the movie before. which skin has this feature?

**Comment by sialivi** [comment]
I think Transparency and Night both support it

**Comment by phil65** [comment]
just tried it in night, and it also doesn´t look good there IMO. also has these fading issues. will wait for pix´s opinion.

**Comment by sialivi** [comment]
If it can't be done in a nice looking way, it's better not to do it at all. Might also introduce unnecesary complexity to the skin. Consider this a low priority feature request.

**Comment by phil65** [comment]
won´t add it then, will close this.
