### ISSUE TITLE
Showcase Settings Not Loaded Correctly

### ISSUE THREAD

**Issue by mark007** [pix/aeon#152]
Hi,

Using latest aeon as of today 17th of Sept, the lovely new gui settings available for each view, don't retain their settings after xbmc reload.

For example I have info set to "Auto", timer set to "2 seconds", style set to the one where extrathumbs are loaded in one window, yet when I navigate to these settings in movies - showcase, they seem to appear as if they are at "Off", "1 second" etc, basically they seem to revert to the topmost (visually) yet I think the ACTUAL settings are being loaded as my info is being shown automatically after 2 seconds etc...

**Comment by mark007** [comment]
EDIT: Let me know if screenshot required. Is it possible for these sub menu settings to filter out to another submenu... just took me a couple of attempts to figure out I needed to hit return to get the options for each.. was expecting another lovely submenu to pop out like before..

**Comment by phil65** [comment]
focusing the currently chosen setting would require to add a lot of invisible buttons, don´t know if that´s worth the effort.

**Comment by mark007** [comment]
Oh right, but in older versions of aeon65, very recently, I could go in and see what my currently set settings were... ie 2 seconds... it didn't always indicate I was using the first item in the list.

Its only recently this has started happening so I wonder how it was done then?

**Comment by phil65** [comment]
no, in older versions Aeon "remembered" the list position, but only until you close XBMC. This behaviour led to other problems (has to do with the changing items in the submenus). Nonetheless, I´ll think about it again.
