### ISSUE TITLE
Film studio fallback image

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#154]
In a recent commit the film studio icon, that's shown in various places such as the bottom of the Multiplex view, received a fallback image of a clapperboard. Could this be removed please? None of the other images shown in these places (such as Aspect Ratio, Format, Sound Format, Resolution etc) has fallback images so it feels rather out of place just to have a fallback image for this one. I'm also against adding fallback images for those other labels I mentioned.

**Comment by phil65** [comment]
the other ones don´t really need them, they´re always visible. 
however, i´m also not really a fan of this, i would have nothing against removing it.

**Comment by mindweaver** [comment]
Yeah I would also be ok with the removal of the fallback image.

**Comment by phil65** [comment]
removed it, closed
