### ISSUE TITLE
Back button doesn't work on add-on changelog screen

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#159]
You can't exit the add-on changelog screen using the back button, you have to use the esc key which feels a bit inconsistent

**Comment by phil65** [comment]
has to be done with keymap.xml, not a skin related thing.

**Comment by sialivi** [comment]
Are you sure you're not misunderstanding me? Why would the keymap disallow me from using the back button on that particular screen when it can be used everywhere else in the add-on screens? Sounds like a very odd design.

**Comment by phil65** [comment]
that´s probably because it´s a dialog, so you have to adjust that part of the keymap.xml

**Comment by phil65** [comment]
just tested, here it closes using either backspace or escape.

**Comment by sialivi** [comment]
With the default keymap? And you are at the "Change Log" screen, right? Not just the add-on screen.

**Comment by phil65** [comment]
yes, should work with the default keymap. i could however add that the dialog closes when pressing left or right, we don´t have any control over the backspace or escape button.
