### ISSUE TITLE
Navigation bug on add-ons screen

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#160]
Steps:
1) Go to the Add-ons screen, the list on the right side ("Available Updates", "Enabled Add-ons", etc) has focus.
2) Press Right.
Result: Nothing seem to have focus, pressing Up/Down/Enter doesn't do anything.
3) Press Left or Right.
Result: Focus is returned to the list on the right ("Available Updates", "Enabled Add-ons", etc)

**Comment by phil65** [comment]
will be fixed

**Comment by phil65** [comment]
fixed in font_rework
