### ISSUE TITLE
Filename not shown when playing non-library videos...

### ISSUE THREAD

**Issue by Shinu** [pix/aeon#162]
Opening the OSD (pressing the "I" key) while view a video that's not part of the library doesn't display the name of the file anymore. Just the length of the vid, screenshot and current and end time. So there's no way to know what video is playing.

http://img97.imageshack.us/img97/1428/9102010104246pm.jpg

**Comment by sialivi** [comment]
There's allready a ticket (#147) discussing improvements to that info screen, might be better to take it up there

**Comment by phil65** [comment]
fixed in Aeon65 v2.0
