### ISSUE TITLE
[Patch] add Arial font set

### ISSUE THREAD

**Issue by taxigps** [pix/aeon#164]
Add a font set only use full unicode range font arial.ttf to support chinese language and others.

see here:
http://pastebin.com/YLUDSPrm

**Comment by pix** [comment]
We're in the process of switching fonts, as you can see here: http://github.com/pix/aeon/tree/font_rework

It's not finished a may be a little buggy. Can you tell me if This branch is ok for chinese characters ? (On my HTPC it display Thai and Japanese fine, I don't have Chinese-Tagged audio so....)
