### ISSUE TITLE
Navigation bug on TV info screen

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#165]
Steps:
1) Enter TV Shows section
2) Press 'i'
3) Select "Downloads"
4) Exit the "Choose what to download" dialog without selecting anything
Result: You are returned to the info screen but no further navigation is possible until you press 'esc'

**Comment by phil65** [comment]
you mean the Dialog "Download cancelled by User"`?

**Comment by sialivi** [comment]
If you mean step 3, it's the "Choose what to download" dialog

Edit: I updated the steps for clarification

**Comment by phil65** [comment]
do you select what do download or do you exit that before by pressing backspace?

**Comment by sialivi** [comment]
I don't select anything, I try to exit right away by pressing backspace or esc

**Comment by phil65** [comment]
Isn´t a dialog saying "Download cancelled by User" appearing for you then?

**Comment by sialivi** [comment]
nope
I'm still on the master branch if that matters

**Comment by phil65** [comment]
try it in font_rework branch, possible that that dialog is invisible for you, changed something in that direction in font_rework.

**Comment by sialivi** [comment]
Looks like it works in font_rework

**Comment by phil65** [comment]
ok, I´ll close it then.
