### ISSUE TITLE
Navigation bug in file browser

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#166]
Steps:
1) Enter "Videos"
2) Press 'c'
3) Select "Edit source"
4) Press Down until you reach "Ok"
5) Press Down again
Result: The selection wraps around to "Browse" instead of "Set content"

**Comment by sialivi** [comment]
There is also a navigation inconsitency here. Pressing Right repeatedly switches back and forth between the Paths on the left side and the options on the right side. However, pressing Left repeatedly only switches to the paths on the left side.

**Comment by phil65** [comment]
thx, got that, will fix it in font_rework branch.

**Comment by phil65** [comment]
fixed
