### ISSUE TITLE
Code for logo fallback in seekbar

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#167]
there are 2 instances for the same scenario (seasons in subfolders):
$INFO[Player.FolderPath]/../logo.png

One should be $INFO[Player.FolderPath]/logo.png

...so if no clearart -> then fallback to logo (even video files are arranged in season subfolders or not)

This goes to master and font_rework too.

**Comment by phil65** [comment]
will be fixed in font_rework, thx
