### ISSUE TITLE
Link main menu item TRAILERS to the official trailers addon.

### ISSUE THREAD

**Issue by mindweaver** [pix/aeon#17]
Apple Movie Trailers - Lite is now submitted to the official add on repository. That means we do not need to use the hacked version. With that we have to change the linking from main menu TRAILERS item to the "real" plugin instead.

**Comment by mindweaver** [comment]
Fixed!

**Comment by chanders** [comment]
We also need to remove the skin settings option asking for the same!

**Comment by mindweaver** [comment]
Please be more precise :)

**Comment by chanders** [comment]
:)

http://img204.imageshack.us/img204/294/screenshot000medium.jpg

**Comment by mindweaver** [comment]
Those are two completely different scripts. But since there is no working copy of YouTrailer for the new addon system we can disable that option for the time being.
