### ISSUE TITLE
Thumbs use banner graphics, causes incompatibility between skins.

### ISSUE THREAD

**Issue by ameinild** [pix/aeon#172]
Ok this is a little tricky, but I'll try. Under TV Shows, the skin has a setting for Thumb, just like Confluence. The main problem here is that the Confluence thumb is a wide banner, while the Aeon thumb is a poster or DVD cover. This means that all your TV shows will have the wrong thumb in Aeon, since they are set to a wide banner.
I think Aeon should use another graphic for the DVD cover, so that you can preserve the wide banner for Confluence, in addition to the DVD cover for Aeon. Does this make any sense?

**Comment by phil65** [comment]
Aeon65 supports poster sized thumbs (can be activated in scaper settings) or landscape.jpg (16:9 Format) at the moment, one or two banner views will be included in Aeon65 v2.0
