### ISSUE TITLE
Option to replace background with currently playing video.

### ISSUE THREAD

**Issue by SSMI** [pix/aeon#173]
In some skins when you go to the home screen while a video is playing it replaces the background.  This could also replace possible some of the fanart and other backgrounds while browsing you media.

**Comment by phil65** [comment]
included in Aeon65 2.0

**Comment by SSMI** [comment]
Is that the current version?  If not when will it be out?

**Comment by phil65** [comment]
in 2-4 weeks I think.

**Comment by SSMI** [comment]
Thanks for the help. This is a great community.  Support here is great.  Can't wait for 2.0.  I would love to be some help if it is possible.  Either testing or working with some small things.  i don't know much about xbmc skinning but know some programming and am available.
