### ISSUE TITLE
Studio logos for music not showed

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#18]
I don't remember if they ever worked, but for now i don't have labels/logos for studios that produced music albums: examples -> Warner, Atlantic, WEA etc. The flags, however, are present in skin structure, so, must be an issue somewhere...

**Comment by sergiocos** [comment]
No logos for music studios

**Comment by pix** [comment]
Reopened :)

**Comment by mindweaver** [comment]
They are there in the code. But I don't think they were ever used or implemented. I don't think I have the time or skill to find out how to put them in there.

**Comment by pix** [comment]
I saw them in the list view, I think, when you browse by albums.

**Comment by mindweaver** [comment]
Can you point me to a specific mainstream album where they are shown? so that I can check?

**Comment by pix** [comment]
When i'll be home, i'll do

**Comment by pix** [comment]
I can seems to find where I've seen them ! May I allucinated ?

**Comment by pix** [comment]
They shows now in low list

**Comment by mindweaver** [comment]
nice work :)

**Comment by pix** [comment]
Closing
