### ISSUE TITLE
Audio menu not working during MKV playback (Cant change audio language) 

### ISSUE THREAD

**Issue by the-speedmax** [pix/aeon#182]
Hi when I listening a movie with multi audio (Ex: English & French) there is no way to get the audio menu working. It works well with the Video menu.

There is a link to the menu (Picture) I talking about.

Audio: http://passion-xbmc.org/aeon/leger-probleme-avec-aeon-65-depuis-la-rc1-de-dharma/?action=dlattach;attach=4842;image

Video: http://passion-xbmc.org/aeon/leger-probleme-avec-aeon-65-depuis-la-rc1-de-dharma/?action=dlattach;attach=4844;image

Has you can see, in the audio playback menu, I do not have the selection bar (Horizontal light grey bar) like in the video playback menu.
I hope it can be resolve... I really like this skin. Thanks for your great work!

Regards, Max

**Comment by res0nat0r** [comment]
I'm having the same issue.

**Comment by pix** [comment]
This should be fixed now in master and font_rework branch.

**Comment by the-speedmax** [comment]
Tested and working! Thanks pix,
