### ISSUE TITLE
Wiki instructions for linux update are incorrect

### ISSUE THREAD

**Issue by diafygi** [pix/aeon#186]
This is a minor bug. The update [instructions for linux](https://github.com/pix/aeon/wiki/Linux-Download-Instructions) in the wiki has an incomplete folder name.

cd ~/.xbmc/addons/skin.aeon

should be

cd ~/.xbmc/addons/skin.aeon65

**Comment by pix** [comment]
On Fri, Mar 18, 2011 at 4:15 PM, diafygi <
reply@reply.github.com>wrote:

> This is a minor bug. The update [instructions for linux](https://github.com/pix/aeon/wiki/Linux-Download-Instructions) in the wiki
> has an incomplete folder name.
> 
> cd ~/.xbmc/addons/skin.aeon
> 
> should be
> 
> cd ~/.xbmc/addons/skin.aeon65
> 
> Thanks, this is fixed

## 

Camille Moncelier
http://devlife.org/

If Java had true garbage collection, most programs would
delete themselves upon execution.

**Comment by diafygi** [comment]
Thanks
