### ISSUE TITLE
Refresh bug when returning to XBMC from external player

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#19]
Setup coreplayerfactory to launch any player you want (I use MPC-HC as ext player). Set movie view to old multiplex/new multiplex. Launch a movie. Now close the external player and let XBMC regain focus. Once XBMC regains focus, it refreshes the window. Depending on the situation, sometimes the overlay would flashes. Sometimes the a certain animation will be activated.

**Comment by pix** [comment]
Is this Aeon65 specific ?

**Comment by pix** [comment]
No response from user, I'm closing this.
