### ISSUE TITLE
Pressing UP does not show Trailer

### ISSUE THREAD

**Issue by chanders** [pix/aeon#22]
There is a label in some of the movie views that says "Press UP to view Trailer" however when pressing UP the side menu becomes visible. The only way to view the trailer is to press I and get to the movie info then select watch trailer.

Suggestion: Change the keybinding to something other than UP to view the trailer and change the label in the view.

**Comment by mindweaver** [comment]
Pressing up activates the "Press select to view trailer" then the trailer plays.

**Comment by chanders** [comment]
If I press up on this screen the menu on the left shows. The trailer does not show.

http://img6.imageshack.us/img6/4938/screenshot000qr.jpg

**Comment by mindweaver** [comment]
ah, in old multiplex.

**Comment by chanders** [comment]
Works great now!

**Comment by pix** [comment]
In old mutilplex, trigger need to be set to on otherwise, the left menu shows.

**Comment by mindweaver** [comment]
trigger can be set to auto aswell. You have to choose a info setting before it kicks in. If you only change to Multiplex Old and do nothing it won't work. Closing this since it isn't really an issue.

**Comment by Orbi** [comment]
I understand this is not an issue but it reduces the overall usability of the skin for the less savvy user. This only happens in multiplex.
