### ISSUE TITLE
Info in 'Trailers' menu item needs to be changed

### ISSUE THREAD

**Issue by chanders** [pix/aeon#24]
http://img687.imageshack.us/img687/6161/screenshot001ks.jpg

Suggestion: Change to "Please install YouTube Lite Add-On to view Trailers"

**Comment by mindweaver** [comment]
don't know if that is possible.

**Comment by chanders** [comment]
Isn't it text? Or is is an image?

**Comment by mindweaver** [comment]
I believe it is text but it is a generic message from XBMC. not skin related. Would be nice if we could override it somehow

EDIT: It is in the skins language files. I'll see if there is a way we can check wether it is the trailer plugin that tries to access the video viewtypes or the actual video library.

**Comment by chanders** [comment]
Cool

**Comment by mindweaver** [comment]
Fixed :D
