### ISSUE TITLE
Make File Manager Accessible

### ISSUE THREAD

**Issue by chanders** [pix/aeon#28]
Couldn't find a shortcut for the filemanager anywhere

**Comment by mindweaver** [comment]
It's on the shortcut/shutdown menu. You can reach it by pressing S

**Comment by CaptInsano** [comment]
how about an option for a Main Menu Shortcut for remote control users!! 

Its a pain having to get the keyboard to play something off a usb quickly

**Comment by pix** [comment]
I have this menu on my remote, mapping missing ?

**Comment by mindweaver** [comment]
Yeah, you should really map this to your remote. I use this meny ALOT. It has Settings and Favourites on it aswell.
