### ISSUE TITLE
When initiating music playback from recently added items; CDArt fails and appear "offscreen"

### ISSUE THREAD

**Issue by pix** [pix/aeon#3]
It's a problem with CDArt on the home screen. (You must have CDArt enabled)

To reproduce:
- Go to music item on home screen
- Press up to see recently added items
- Select one album and press play.

The CDCase is half offscreen on my setup

**Comment by mindweaver** [comment]
Closed by cba6851fe8eff8a05d3bfc4a89673114493e2063: When initiating music playback from recently added items; CDArt fails and appear "offscreen"
