### ISSUE TITLE
Some weather animated images not shown in Home

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#33]
If the weather condition images are set to ANIMATED, some of them aren't shown. I looked at the fanart weather pack and i found out discrepancies in naming folders. The fix is to rename the folders starting with digit '0' from 'media/icon/' folder and remove the 0 digit. This way '01' became '1' and so on ... '09' became '9'. I like also a color convention for temperatures, like in my image:
http://img571.imageshack.us/img571/1412/screenshot001m.png

**Comment by sergiocos** [comment]
i knew i'm not the only one :P
http://forum.xbmc.org/showpost.php?p=295499&postcount=103

**Comment by pix** [comment]
Renamed weather meida icons

Closed by 60820c3e04bc34d8346959937c25d362c74dc67b
