### ISSUE TITLE
Missing Sound Flag (DTS, DD5.1, 2.0 etc) in LowList

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#34]
I'm using Ember and i recently see that in LowList i don't have any of the sound flags. However, the sound is recognized (and properly showed in Movie Info, when pressing "i").

**Comment by sergiocos** [comment]
This happens on movies level and also on episode level (tv series)

**Comment by pix** [comment]
There is no sound flag on low list the empty slot next to aspect ratio is the studio flag.

**Comment by pix** [comment]
Nevermind, i found it :)

**Comment by pix** [comment]
Closed by 81958b7b506de24c0618afb9c844fd8a52d13b4b : Missing Sound Flag (DTS, DD5.1, 2.0) in LowList
