### ISSUE TITLE
TV show art not formatted properly

### ISSUE THREAD

**Issue by chanders** [pix/aeon#37]
http://img96.imageshack.us/img96/4303/screenshot001resized.jpg
http://img821.imageshack.us/img821/348/screenshot002resized.jpg
http://img59.imageshack.us/img59/3216/screenshot003resized.jpg

**Comment by mindweaver** [comment]
You have to have the correct image ratios for the view you want. if you choose poster view you have to have a poster as folder.jpg and so on.

**Comment by chanders** [comment]
Agreed, but Aeon uses a non standard size in this view since XBMC does not support this size natively. So the user has to manually download these files one by one.

Suggestion: Modify the view to use banners which are natively supported by XBMC using this simple mod

http://forum.xbmc.org/showthread.php?t=54825

**Comment by mindweaver** [comment]
Chaning this to a feature request. Where you request the addition of the bannerplex mod as a new view or addition to the multiplex view :)

**Comment by chanders** [comment]
Thanks!

**Comment by TiN-MAN** [comment]
How about something like the banner wall in Legacy Dark?

http://thegeekstreet.com/wp-content/uploads/2010/05/screenshot012j.png

**Comment by StarrrLite** [comment]
That would be awesome!
I think Aeon really needs a banner view for tv-shows, as a lot of people CBA to download banners for ALL their tv-shows manually

**Comment by kraaa** [comment]
I still have this issue. Fixed it before by removing my database and scan it again but now it just showed up after an update to aeon i think.

**Comment by ghost** [comment]
Use Ember To Scrape your TV shows, then you have full control over all images.

**Comment by StarrrLite** [comment]
I am using ember at the moment, I have set ember to scrape posters instead of banners, but XBMC is still showing banners :S
I personally prefer banners tho, as the horizontal layout makes for much bigger fonts in the banners, making it easier to regocnize my shows on my TV.

**Comment by ghost** [comment]
How does the folders with your TV Shows look then? XBMC shows whatever image Ember put there, if it's named correctly. I have no problem with this.

**Comment by pix** [comment]
Now, For 3:2 aspect ratio views, you can put a folder.jpg image and activate the setting in advanced settings. (These image are automaticaly downloaded by script.logo-downloader-something)

**Comment by kraaa** [comment]
My issue was the download folder.jpg i had for my shows. Any way to disable this for tv-shows or its either movies and tvshows or nothing?

**Comment by phil65** [comment]
yes, you can change that via advancedsettings.xml
