### ISSUE TITLE
Video menu item is labeled 'Movies'

### ISSUE THREAD

**Issue by chanders** [pix/aeon#39]
http://img6.imageshack.us/img6/9094/screenshot004pn.jpg

**Comment by mindweaver** [comment]
Mine does not say MOVIES. When I enter VIDEOS it says TV. 

So there is definitely a bug there somewhere.

**Comment by mindweaver** [comment]
Closed by 0cb66bd3a02d39424511832a3b8b2ec438ea1a0f: Video menu item is labeled 'Movies'
