### ISSUE TITLE
Music Track Duration text not center on y-axis

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#4]
*Reproduce by playing a track, then go to main menu. Highlight "PLAYLIST" and wait for duraton to show

**Comment by mindweaver** [comment]
Do I need to have something else activated in options. Because I get no duration popup when highlighting PLAYLIST in main menu.

**Comment by chanders** [comment]
If you don't press any key it should show up after a while.

**Comment by mindweaver** [comment]
http://tillytech.se/where.jpg

where should it appear on that screen?

**Comment by pix** [comment]
[PLAYLIST] Funny, I never saw that menu, I always used my remote :)

**Comment by mindweaver** [comment]
Yeah, I recently discovered it aswell :) like a week ago. Can't believe I missed it hehe.

**Comment by pix** [comment]
You mean this: http://imgur.com/BZVOJ.png ?

**Comment by chanders** [comment]
I think thats exactly what he/she is talking about. But it looks centered to me :/

**Comment by kin0kin** [comment]
Yes that's the one. X axis is centered, Y is off by a few pixels. Looks quite centered in the picture pix posted, but certainly not on mine. Anybody knows which is the responsible xml?

**Comment by mindweaver** [comment]
Includes_MainMenu.xml

It differs depending on resolution :(

**Comment by mindweaver** [comment]
Closed by 8afa5fe4d532efc69f58dfde268647d9b7dc8361: Music Track Duration text not center on y-axis
