### ISSUE TITLE
CDArt Spinning Speed in Home or MusicVis

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#40]
In this skin the speed of CDArt is waaay higher then in any other skin. The purpose is to show off the cd label, not to imitate a real cd player.So i suggest reducing the spinning speed in any scenario.

**Comment by sergiocos** [comment]
Also the position of the CDArt might be adjusted, to show the inner transparent size of the CDArt label. http://img267.imageshack.us/f/screenshot002lu.png/

**Comment by pix** [comment]
Closed by 02f64900467e2fe7912de7ec44204116760b1928: CDArt Spinning Speed in MusicVis
