### ISSUE TITLE
TV-Series info in Landscape, thumb view should show poster.jpg, not folder.jpg

### ISSUE THREAD

**Issue by mindweaver** [pix/aeon#42]
TV-Series info in Landscape, thumb view should show poster.jpg, not folder.jpg

http://tillytech.se/poster.jpg

you can see that the image to the left has incorrect aspect.

**Comment by mindweaver** [comment]
Closed by 3d3b356360dcd092ce5c138a50e264414a62907e: TV-Series info in Landscape, thumb view should show poster.jpg (if exists) before folder.jpg/thumb

**Comment by pix** [comment]
Posters stopped working for me since this patch

**Comment by mindweaver** [comment]
please add screenshot so I don't go poking in the wrong area when trying to fix it :)

**Comment by pix** [comment]
http://imgur.com/FvR2Q.png

**Comment by pix** [comment]
If I revert your patch it works

**Comment by mindweaver** [comment]
Is it named poster.jpg ?

**Comment by pix** [comment]
Nope I didn't downloaded anything it the default thumb scrapped by xbmc

**Comment by mindweaver** [comment]
Ok. I must have missed the fallback then. I will fix it :)

**Comment by mindweaver** [comment]
Fixed :)
