### ISSUE TITLE
Missing python DLL bz2.pyd

### ISSUE THREAD

**Issue by rezyn8** [pix/aeon#43]
Using http://www.sshcs.com/xbmc/binaries/tmp/XBMC_PCInstaller_31746.rar

Package does not appear to have the bz2.pyd DLL - something I came across when trying to use Apple Movie Trailers Light|Lite (Official XBMC Add-on and http://forum.xbmc.org/showthread.php?t=33693)

Log:

00:46:15 T:6212 M:2549800960   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Apple Movie Trailer Light('plugin://plugin.video.applemovietrailerlight/','0','')
00:46:15 T:6212 M:2549800960    INFO: initializing python engine.
00:46:15 T:6212 M:2549800960   ERROR: Python: Cannot find 'special://xbmc/system/python/DLLs/bz2.pyd'
00:46:15 T:6212 M:2549800960   ERROR: Python: Missing files, unable to execute script
00:46:15 T:6212 M:2549800960   ERROR: Unable to run plugin Apple Movie Trailer Light

**Comment by rezyn8** [comment]
I retrieved a copy of bz2.pyd from revision 31520 

http://svnsearch.org/svnsearch/repos/XBMC/search?revision=31520&showPaths=all&

This fixed the issue

**Comment by mindweaver** [comment]
Wonder why you even posted about it here :)

**Comment by rezyn8** [comment]
Only because I came across it because of the build I used from this project that pix stated in his opening post on the xbmc forums.

**Comment by pix** [comment]
I changed it to the official builds

**Comment by rezyn8** [comment]
Cheers
