### ISSUE TITLE
LowList: Studio logo for music (in tracks level) appears only when a track is played

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#44]
I noticed that strange behavior for studio logos (music) only gor LowList

**Comment by pix** [comment]
Seems to work for me, screenshot ?

**Comment by sergiocos** [comment]
of course!
before play, no studio logo -> http://img268.imageshack.us/img268/3976/screenshot000q.png
after play, we have a logo -> http://img704.imageshack.us/img704/8996/screenshot001zn.png

when i stop the music, the logo is still showed, but only when that track is in focus, when i move to other track, i have to do the same routine... play that track to have a logo.

**Comment by pix** [comment]
You're lucky to have them, I can't even have them to show when playing, (I see them in album level though)

**Comment by pix** [comment]
It seems that  $INFO[ListItem.Property(Album_Label)] is only available when music is playing when the container contains song. This might be an xbmc bug (or feature :))

**Comment by pix** [comment]
I've filled an XBMC patch[1](http://trac.xbmc.org/ticket/9791), if it gets accepted i'll be able to close this ticket.

**Comment by pix** [comment]
I'll close this ticket, this is not a bug (The required informations are missing, so we can show the information for the other track)
