### ISSUE TITLE
Remove / Replace Artist Name from Showcase

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#45]
You guys are pretty handy at finding things in this xml-monster. Mindweaver told me to post here, so here it goes:
http://img218.imageshack.us/img218/1600/screenshot002qc.png
I wanna get rid of the artist name because I'm still use the template from Showmix (a .psd where i edit the name and replace artist picture). Instead of the artist name i prefer the number of albums. If you have time to tell me what i have to replace and where, i will be grateful. I already spent hours trying to find this... No hurry, i know you have enough on your plates. :)

**Comment by mindweaver** [comment]
It's probably possible to do this as an option.

**Comment by sergiocos** [comment]
It would be nice, dunno however if others need/use that, and that's the only view (ARTISTS)  where the info is redundant. I still need the info in albums/movies/etc. that's why I labeled my req as [PERSONAL]. Thanks for the will to help me!

**Comment by mindweaver** [comment]
Damn I can't find where that label is set. weird.

**Comment by sergiocos** [comment]
I know... Let's put a pin in it and hope you stumble somehow into that label... No need to turn your hair gray for this (like me)

**Comment by mindweaver** [comment]
pix if you can find it, please tell me and I will add the feature :)

**Comment by phil65** [comment]
it´s in include_floortext in the includes_furniture.xml.
I don´t think we should make it an option as it is only makes sense for very few users.

**Comment by pix** [comment]
I agree with you, phil65. I'm closing this request.
