### ISSUE TITLE
Main Menu Link to FileManager

### ISSUE THREAD

**Issue by CaptInsano** [pix/aeon#46]
For ease of use when using a Remote with XBMC a Main Menu Link to FileManager would be great. 

It could hopefully be turned off in Main Menu Settings for those who don't want it.

**Comment by mindweaver** [comment]
Closed by 07fdd07a405108963e5f2cebda789d4a7f765a40: Main Menu Link to FileManager

**Comment by mindweaver** [comment]
Didn't see why we couldn't add it to main menu :) so there you go!
