### ISSUE TITLE
TVShow List view

### ISSUE THREAD

**Issue by chanders** [pix/aeon#47]
If a poster.jpg exists, the skin is supposed to use this instead of the banner. However you can still see the banner being loaded just before the poster shows. It looks like a glitch. Also coming down to the end of the list, poster.jpg isnt being used.

**Comment by pix** [comment]
Isn't the image your seeing the fallback image ?

**Comment by mindweaver** [comment]
There is no fix for this. Since there is no way to check if a file exists. Therefore the icon is loaded first and then the poster. Only fix for you is to choose the poster as thumb for the tv show. then there won't be a glitch

**Comment by chanders** [comment]
Thanks, but there should be a better way without the glitch. 
Suggestion: why not just change the size of the viewable area to show the banner in this view?

http://img96.imageshack.us/img96/4303/screenshot001resized.jpg
