### ISSUE TITLE
Show Cast - Highlights First Actor Incorrectly

### ISSUE THREAD

**Issue by mark007** [pix/aeon#49]
Hi,

When viewing a movies information and when "Show Cast" is selected, it appears as if the first actor is highlighted (aswell as Show Cast). When I press return however the show cast information disappears (indicating the first actor shouldn't be highlighted).

Pressing the down arrow once, after clicking on "Show Cast" is necessary. (This makes show cast be unhighlighted, leaving the first actor highlighted).

The fix would be to either

1) Not highlight the first actor, or 
2) leave it highlighted but when return is pressed, that actors details should appear, and not require the down arrow to be pressed.

**Comment by PBoD** [comment]
Confirmed. Option 1 seems to be easiest, with a default placeholder for the actor photo.

**Comment by pix** [comment]
Fixed
