### ISSUE TITLE
Broken Icons: Music Add-on/Playlist Folder/Add Source icon not aligned properly

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#5]
*Reproduced by going into music, then library mode, and highlight playlist

Someone should completely rebuild the icons

**Comment by mindweaver** [comment]
Music Add-on icon is OK
There is no add source in library mode.

**Comment by mindweaver** [comment]
Closed by 2a4dae099068ee2b1de8e9ce879e81f842aceab0: No fallback image (defaultFile.png)
