### ISSUE TITLE
Show Cast - Navigating to episode doesn't show thumb

### ISSUE THREAD

**Issue by mark007** [pix/aeon#50]
I have clicked Show Cast, on a movie, and navigated from there to an actor, and from there to an episode of a tv show that contains that actor.

When this episode of the tv show appears, the thumbnail for that isn't shown on the left of the screen, like would appear when I manually navigate to that tv show episode and press i.

**Comment by PBoD** [comment]
Reproduced. However, navigating from movies (Serenity) to Nathan Fillion (actor) to Firefly (TV Show) displays show's info panel with poster art to the left, so that works.

**Comment by pix** [comment]
Closed by 7768576d2e4df784a9c5acdf63e67daf157feb8e: Show Cast, Navigating to episode doesn't show thumb
