### ISSUE TITLE
Scroll Animation Not Completing on Multiple Navigation Moves

### ISSUE THREAD

**Issue by mark007** [pix/aeon#51]
Hi,

When navigating through for example movies with showcase, if I press the right arrow, a beautiful animation appears from one movie to the next.

This is fine, but if I press the right arrow, whilst an existing animation is in progress, the animation isn't allowed to complete, instead a jerk effect happens from wherever the old animation left off.

This means a sequence of quick succession of moves, eg right right right right, would give an effect like jerk, jerk, jerk, smooth.

I think the solution is to allow existing animations to complete before another is started, or to speed up ongoing animations, but not completely quit from them....

**Comment by mark007** [comment]
I suppose this applies to all menus including the main menu. When pressing right twice, there isn't two smooth animations, the first one is interrupted, ie jerky, and the second one is smooth. Will make the skin alot more beautiful I think!! Thanks!

**Comment by pix** [comment]
I don't know if it's possible to do this, but i'll leave it open until further investigations.

**Comment by sergiocos** [comment]
Same thing happened to me but the solution seems to be converting .jpg to .dds. The animation will be jerky ONLY the first time the fanart/backdrop is showed, after that will be cached as dds and xbmc will scroll fast like usain bolt.
Test it adding this in your advancedsettings.xml:

<advancedsettings>
        <useddsfanart>true</useddsfanart>
        <restrictcapsmask>4</restrictcapsmask>
</advancedsettings>

**Comment by mark007** [comment]
Sir for 99% of users what's the solution. A feature request in xbmc. I don't thing caching  is the issue though. I just think its the way it's coded. Ie when a new action is started ie move right then currently running animations are ignored.

**Comment by sergiocos** [comment]
Aeon65 was my default skin since always, so I remember all the development steps. Aeon65 was always a hungry skin, but these glitches came with Dharma development. I remember some Dharma builds where Aeon65 was scrolling smooth as always. I noticed the problem since may, but switching to .dds did the trick. Let's wait until a Dharma beta will come up and talk after that.

**Comment by temmi2000** [comment]
fixing this is not possible on skinning level. closed.
