### ISSUE TITLE
Movie Count Not Updating

### ISSUE THREAD

**Issue by mark007** [pix/aeon#52]
Hi, When adding movie directory to xbmc, the progress bar shows movies being added into the library.

The information bar on the home screen doesn't update however to show the number of movies currently in the library, it stays at 0. I think this should update on movie add / removal to more accurately reflect the current movie count..

**Comment by mindweaver** [comment]
Have you installed the recently added plugin correctly?

**Comment by mark007** [comment]
I just installed the skin and xbmc using instructions on the forum. Ie downloading from git and copying skin into xbmc folder. Is there a newer method in the last week?  I'll try to reproduce either ways.

**Comment by mindweaver** [comment]
You have to have script.recentlyadded in your addon folder

**Comment by mark007** [comment]
Yes I have this folder.
C:\Program Files (x86)\XBMC\addons\script.recentlyadded

The number of movies only updated after navigating in and out of a few menus, it stayed at 0 if I only moved around the main home screen. I think it should update from 0 on every movie addition. ie can it hook into or listen to add movie events.

It seems to just load the movie count at certain times, navigating back to the home screen perhaps being one of them.

This is only a new xbmc and skin install within the past week so everything is as it should be.

**Comment by pix** [comment]
Which revision of the skin are you using ? (Show log with TortoiseGit, or git log using GitBash) This should look like this: 
    "b1841a823d05a9e22612bb181fcd3c6bf4141b97"

**Comment by mark007** [comment]
Show Log in tortoise git shows version from 18th of July

Commit:b1841a823d05a9e22612bb181fcd3c6bf4141b97
- Moved backdrops to the extras directory (part of texture cleaning)

When xbmc updates movie database with newly found movies, does this figure automatically update on yours or do you need to navigate in and out of a few menus for the change to become visible?

**Comment by pix** [comment]
```
When xbmc updates movie database with newly found movies, does this figure automatically update on yours or do you need to navigate in and out of a few menus for the change to become visible?
```

It figures automaticaly, yes

Which XBMC build by the way ?

**Comment by mark007** [comment]
31938

I'll update xbmc build, add some more movies, and let xbmc find them, and see does the skin update the count on the fly as the movies get added. I'll report back.

**Comment by mark007** [comment]
Now on xbmc 31980. Added 5 movies to the library directory. Created nfo / extrathumbs etc with EMM.

Opened xbmc, showed the old movie count. Set xbmc to automatically find new content on load. See -> http://img714.imageshack.us/i/screenshot000i.jpg/

Shutdown and restarted xbmc. GUI showed xbmc finding new content, but skin count didn't update. See ->

http://img231.imageshack.us/i/screenshot002vjr.jpg/
http://img441.imageshack.us/i/screenshot007ww.jpg/
http://img42.imageshack.us/i/screenshot008ae.jpg/
http://img338.imageshack.us/i/screenshot009r.jpg/

Still no update to the figure after all are completed.......

After navigating to the tv shows folder, and back out, then the number of movies was visibly seen changing to the correct figure so no, its not automatically updating in my case when a movie is added. See -> http://img828.imageshack.us/img828/5170/screenshot010v.jpg

**Comment by mindweaver** [comment]
I think it is by design. to not have it run in the background and take up resources. I believe it is set in the script, not the skin. but not sure.

**Comment by mark007** [comment]
Wouldn't have thought it would take alot of processing power to have it update.....

But if performance is the reason, it should update at the end of the library update process at least, as its only once...

**Comment by mindweaver** [comment]
yeah. we will have to investigate if it can be done in the skin or if you have to request it over at XBMC or recently added forums.

**Comment by mark007** [comment]
Great, thanks guys! Keep up the good work! Let me know if request is needed over at the forums.

**Comment by phil65** [comment]
cannot be done --> closed
