### ISSUE TITLE
Strange Number Shown Scrolling

### ISSUE THREAD

**Issue by mark007** [pix/aeon#53]
Hi,

When scrolling through all seasons / all episodes of a tv show, a strange number appears that seems to have no meaning in relation to the highlighted episode.

Screenshot below shows when season 7, episode 14 is shown, the number "3" is visible in a little silver box. I assume it should show "7"? I have sort by episode enabled.
http://img838.imageshack.us/img838/5421/21950891.jpg

**Comment by mark007** [comment]
I have reproduced in movies, sorting by anything other than Name, shows a strange letter or number that has no resemblance to the date, rating etc. Sometimes the box is pure black with nothing inside of it.

**Comment by PBoD** [comment]
Is this "Landscape" view? I reproduced this using Voyager series in Landscape view, sorted by episodes. However, the "mystery" numbers only show during a constant scrolling (fast) of the episodes. Same?

**Comment by mark007** [comment]
Yeah they take a few scrolls to show up, I assume thats by design.

**Comment by PBoD** [comment]
i've only been able to reproduce the number 1. How did you get the "3"? Any pattern there?

**Comment by mark007** [comment]
No particular pattern that I can see. Maybe developers will understand. In any case the numbers don't seem to show anything relevant in many views and sort by types.

**Comment by PBoD** [comment]
Scratch my last. Scrolled in Voyager, found repeating numbers 1,2,3,4,8 (out of seven seasons).

**Comment by PBoD** [comment]
Breakdown: In Movies->Multiplex view
sorted by Rating: numbers appear 1-9 sequentially
sorted by Year: blank box
sorted by Runtime: numbers appear 1-9 _mostly_ sequentially (switches numbers)

**Comment by phil65** [comment]
The feature you are talkin about is called Auto Scroll Letters and shows

"$INFO[ListItem.SortLetter]</label>"

it should return the first letter of the highlighted item and helps to get to the right letter in large libraries by holding a button. If a wrong letter is shown, then it is xbmc related, nothing to do with the skin.

**Comment by pix** [comment]
> sorted by Year: blank box

Thats a bug :) 

```
<visible>!IsEmpty(ListItem.SortLetter)</visible>
```

Should make it disappear..

**Comment by mark007** [comment]
So is a xbmc bug report required.

Just wondering is the feature designed to help scrolling when sorted by year rating etc. If so I imagine first number of rating could be used, last two digits of the year if thats not how it is designed already?

**Comment by ghost** [comment]
This works just fine for me, even when i scroll for rating and year.

**Comment by mark007** [comment]
Actually the only ones I see an issue with now are sort by runtime and year.

Sorting by runtime is fine but the little box isn't useful in this situation if it only shows the first digit, with some runtimes having two digits (eg 136 minutes) and others containing two characters (95 minutes). So the box isn't helpful when scrolling in this case as the number changes to like 1........8.....1.......9.......

And of course for year, it just shows a black box at present. If it could show the last two digits in this case it would be wonderful!

**Comment by pix** [comment]
Closed by 14f3fde6ca79482a7c07afe64ab67469ab6b7070: Strange Number Shown Scrolling

> ListItem.SortLetter
> 
> > Shows the first letter of the current file in a
> > list or thumb control

2 is the first letter of 2010, So we can't do much better for now
(We could slightly improve it but it would be a feature request :)

This should fixed the blank box by the way.

**Comment by mark007** [comment]
Thanks alot! Shall I add a seperate feature request to have the last two digits shown when sorting by year or will this ticket be enough to cover it also?

**Comment by pix** [comment]
You may add a featue request, I don't know if it's possible tough...

**Comment by mark007** [comment]
Hi, This doesn't seem to be fixed in all locations. EG today with latest aeon as of 7th Aug, I went to movies in the main menu, pressed the down key and selected genres to try the new genre art (sweet!), then sorted by year.

When scrolling here for example, a black empty box is seen... so maybe the solution in one location could be replicated in other places that it might apply, possibly many?

**Comment by pix** [comment]
Closed by 549a3a1fb6b58c82528162673c40e2d1c2d214d2: Strange Number Shown Scrolling

I also added the full year instead of first digit

**Comment by mark007** [comment]
TYVM!

**Comment by mark007** [comment]
Hi pix, I'm afraid now that an xbmc bug has been fixed http://trac.xbmc.org/ticket/9881 to allow scrolling by episode, this aeon report now applies to it also. ie scrolling by number of episodes on in aeon65 just shows a "1" in the black box. http://img825.imageshack.us/img825/7483/scrollbyepisodes.jpg
