### ISSUE TITLE
TV Show list view is messy when summaries contain newlines

### ISSUE THREAD

**Issue by wwall3r** [pix/aeon#54]
An episode whose summary contains a newline does not flow correctly in the view. Perhaps replace newlines with some character delimiter such as "|" or "//" ?

**Comment by pix** [comment]
Screenshot ?

**Comment by wwall3r** [comment]
http://tinypic.com/r/2hx6rh1/3

**Comment by PBoD** [comment]
Confirmed. Reproduced using native scrape from XBMC of "Doctor Who" (same in plaguester's screenshot?)

**Comment by PBoD** [comment]
Same result with Star Trek: Voyager series.

**Comment by pix** [comment]
Closed by c34c164953641d3f7014f6cec56a95d61f4306ec: TV Show list view is messy when summaries contain newlines
