### ISSUE TITLE
Not finding poster.jpg

### ISSUE THREAD

**Issue by mark007** [pix/aeon#55]
Using XBMC 32049, latest aeon65 skin as of 22nd of July.

I have had to rename all of my poster.jpg files to folder.jpg because the poster.jpg's arn't been seen by the skin. poster.jpg worked perfectly with old pre 10 xbmc.

**Comment by pix** [comment]
This might be related to 3d3b356360dcd092ce5c138a50e264414a62907e, any ideas mindweaver ?

**Comment by pix** [comment]
Can you reproduce this with a version older than  3d3b356360dcd092ce5c138a50e264414a62907e ?

**Comment by mark007** [comment]
Yes I used the xml of that file previous to the changes in http://github.com/pix/aeon/commit/3d3b356360dcd092ce5c138a50e264414a62907e and reloading a movies data doesn't find poster.jpg again. Had to rename back to folder.jpg and reload. Can you reproduce?

**Comment by pix** [comment]
Can you give me a sample xml file ?

**Comment by mark007** [comment]
Use the latest xml available, you should be able to reproduce.

**Comment by pix** [comment]
Nevermind, i thought you were using some kind of media manager, and that was related to this bug, I need some sleep // or more coffee

**Comment by pix** [comment]
Can you post a detailed step by step procedure in order to reproduce the behaviour ? I'm surely missing something and I have a hard time trying to reproduce this.

**Comment by mark007** [comment]
No problem. Here are screenshots of a folder structure for one movie which I just reproduced on. See two images, one containing poster.jpg, one containing folder.jpg.
http://img168.imageshack.us/i/posterqq.jpg/
http://img265.imageshack.us/i/folderj.png/
So I edited my poster temporarily to have red squiggly lines in it, so that I can distinguish my local poster from any that xbmc might magically download from the internet.

Here is image 1, using my old folder.jpg file, perfect -> http://img695.imageshack.us/i/59039492.jpg/
Here is image 2, using a newly edited folder.jpg showing the red squiggly lines, and xbmc correctly loads it up after I hit readload, perfect -> http://img265.imageshack.us/i/38969515.jpg/
Here is image 3, with this folder.jpg renamed back to poster.jpg, xbmc doesn't see it at all on reload, bug -> http://img835.imageshack.us/i/77649632.jpg/

In showcase view (not the information dialog), xbmc actually shows what looks like a frame from the movie as a poster in this case where it doesn't show any poster in "information". I suppose thats a new bug that I can report after this one is hopefully resolved.

**Comment by pix** [comment]
I may have a fix but i have to ask something to mindweaver before, cause I don't know whey he changed  Path to FileNameAndPath

**Comment by mark007** [comment]
Does this also effect tv shows, as tv show posters called "folder.jpg" no longer seem to be read in the info panel for the tv show. The info panel seems to load up an old cached version of this poster which I no longer even have on my pc. Multiple reloads of the tv show (saying yes to reload for all episodes) doesn't help.

The new folder.jpg file shows up perfectly in tv shows library view, just not in the info panel.

**Comment by pix** [comment]
I made some changes, Can you tell me if its better ?

**Comment by mark007** [comment]
Thank you, folder.jpg now shows up in info... I assume aeon now handles all xbmc poster / fanart formats? Trying to search through the wiki for all supposidly supported filenames but not having much luck finding info for posters....

As I mentioned in my other ticket, now folder.jpg shows but aeon still shows an xbmc / old cached image first... can this be prevented if folder.jpg exists, ie have aeon now show whatever is shown currently before the fanart.jpg animation begins. An animation is seen loading folder.jpg on top of an old cached image....

And as mentioned in my other ticket, folder.jpg doesn't show up in its original form. A highly scaled down version of folder.jpg is seen. I guess one or both of these tickets should be closed? No point having two discussing this same issue of old cached images and scaled down versions of fanart.jpg which are my remaining issues  http://github.com/pix/aeon/issues#issue/90

Apologies for any duplication of information / questions.

**Comment by pix** [comment]
> can this be prevented if folder.jpg exists

There's no way currently to check if a texture exists or not, so we can't hide the other image displayed before...

As requested, closing, See #90

**Comment by mark007** [comment]
Thank you, so I think both quality of folder.jpg aswell as this old cached image problem should both go on trac... reporting now. If nothing aeon can do I think you could also close off this ticket...
