### ISSUE TITLE
Cast List Appearing Twice - TV Show Episodes

### ISSUE THREAD

**Issue by mark007** [pix/aeon#57]
Using XBMC 32049, latest aeon65 skin as of 22nd of July.

When viewing the cast for a Tv Show episode, the cast list is shown twice. This bug was also present many months ago in pre 10 xbmc versions and skin. See here duplicated names -> http://img228.imageshack.us/img228/1411/screenshot002pi.jpg

**Comment by pix** [comment]
I cant reproduce this behavior (I tested a couple of movies and TV shows) Are you using some thing like a media manager instead of XBMC TVDB scrapping ?

**Comment by mark007** [comment]
Yes using ember media manager. So have an nfo for tv show, season, episode.

Episode nfo contains only four actors, but xbmc displays all four twice, so I see 8 in the cast list. See output from nfo below, for the episode.

  <actor>
    <name>Dermot Morgan</name>
    <role>Father Ted Crilly</role>
    <thumb>http://thetvdb.com/banners/actors/41439.jpg</thumb>
  </actor>
  <actor>
    <name>Ardal O'Hanlon</name>
    <role>Father Dougal McGuire</role>
    <thumb>http://thetvdb.com/banners/actors/41441.jpg</thumb>
  </actor>
  <actor>
    <name>Frank Kelly</name>
    <role>Father Jack Hackett</role>
    <thumb>http://thetvdb.com/banners/actors/41442.jpg</thumb>
  </actor>
  <actor>
    <name>Pauline McLynn</name>
    <role>Mrs. Doyle</role>
    <thumb>http://thetvdb.com/banners/actors/41440.jpg</thumb>
  </actor>

Perhaps xbmc imports all of the nfos but forgets to remove duplicates, ie all actors obviously exist in the tv show nfo, then some in the season nfo, then perhaps less in a particular episode nfo.... If you believe this could be the cause, perhaps it should be an xbmc bug report?

**Comment by pix** [comment]
If think this is a scrapper issue. Try this in Confluence, if confluence shows 8 entries then it's an xbmc/scrapper issue.

I'm waiting until your answer in order to close it.

If you want to report the problem on XBMC bugtracker it's here: http://trac.xbmc.org/ and here http://trac.xbmc.org/report (Login with your forum credentials)

**Comment by mark007** [comment]
Confirmed to also happen with confluence. I'll move the details over to xbmc trac. Thanks!
