### ISSUE TITLE
Ordering Cast List

### ISSUE THREAD

**Issue by mark007** [pix/aeon#58]
Hi, Perhaps this is a feature request, or a bug, I dont know.

Can the cast list be ordered in the order they are found in the nfo file. For example. I have a movie, Goldeneye featuring Pierce Brosnan.

I downloaded all of the information using Ember Media Manager, including the full cast, which EMM orders in its GUI and in the nfo created, in the order in which it finds those actors on the imdb page. So XBMC and aeon65 display this data beautifully, but I wanted to go into cast, and see the main actors assuming aeon65 would also list this cast list in the order imdb, emm, and the nfo file list them.

Instead the actor list seems to be randomly mixed up, leaving it hard to find particular actors, and impossible to interpret the key actors by the order they appear.

Can the skin order the cast list in the order they are found in the nfo file like Ember Media Manager does?

**Comment by pix** [comment]
This is a feature request for XBMC as the skin do not control the order of the elements. Which are store in ListItem.CastAndRoles if i remember correctly. So I'm closing this.
