### ISSUE TITLE
Missing Plot - Revert To Plot Outline

### ISSUE THREAD

**Issue by mark007** [pix/aeon#59]
Hi, This is a feature request.

Many of my movies have nfos that don't contain a plot (because none existed on imdb) and so only have a plot outline.

Can the plot shown in the skin revert to the plot outline if the plot is empty. This would be fantastic for those movies that don't have a plot.

**Comment by pix** [comment]
Which view ? All of them ?

**Comment by mark007** [comment]
I'm using showcase but I guess the feature request could apply to any.

**Comment by pix** [comment]
Closed by 12f54de9d8c19c20fa8ac95dfd969308b93724b7: Missing Plot, Revert To Plot Outline in Showcase

**Comment by mark007** [comment]
tyvm!

**Comment by mark007** [comment]
just wondering, is it supposed to show the tagline rather than the outline? I'm seeing the tagline instead of outline...

Ie for the movie cop out which I don't have a plot for, I have a plot outline and a tagline.

I see tagline "Rock out with your Glock out" rather than "A comedy about a veteran NYPD cop whose rare baseball card is stolen. Since it's his only hope to pay for his daughter's upcoming wedding, he recruits his partner to track down the thief, a memorabilia-obsessed gangster". What do you think.

**Comment by pix** [comment]
Fixed, now try: Plot, PlotOutline then Tagline

**Comment by mark007** [comment]
Wow perfect, thanks alot. I really appreciate all of these fixes. Skin getting really really good!!

**Comment by mark007** [comment]
Hi pix, this seems to have reverted to the old behaviour. Using latest aeon as of 9th August. When opening a movie that has a plot outline but no plot, the info dialog says "PLOT DETAILS UNAVAILABLE".
