### ISSUE TITLE
Movies Multiplex not showing year/IMDB

### ISSUE THREAD

**Issue by PBoD** [pix/aeon#60]
(Not sure if this is a scraper/XBMC issue or not, first "issue", sorry)

The year and IMDB rating (either text or stars) is not displaying in Multiplex view.
Screenshot: http://i.imgur.com/4ChVJ.jpg

**Comment by pix** [comment]
Is it displayed for the same movie in another view ?

**Comment by PBoD** [comment]
Yup, both year and IMDB rating are displayed in Multiwall view
Screenshot: http://imgur.com/O2C8a.jpg

**Comment by pix** [comment]
Closed by cf6c9045bd2bfda480343843e7c52e8d19143de7: Movies Multiplex not showing year/IMDB

**Comment by PBoD** [comment]
It is the same for all movies. Also, it seems the "Fanart/Thumb" style displays the IMDB rating, but not the year (http://imgur.com/mXgkH.jpg).

**Comment by pix** [comment]
Too late PBoD, it's already fixed :-)
