### ISSUE TITLE
Video settings not avalaible

### ISSUE THREAD

**Issue by hbooo** [pix/aeon#61]
On confluence, when I read a video, I can go to video settings of the current video by using OSD.

On Aeon I can't

**Comment by pix** [comment]
You mean this settings: http://i.imgur.com/2jE7Q.jpg ? Using the mouse isn't supported on Aeon, You have to use the keyboard. I'll reopen if the bug is caused by something else.

**Comment by hbooo** [comment]
Yes, that was this menu, thanks for the answer and sorry for the ticket
