### ISSUE TITLE
No default background image for "Files" shortcut in Main Menu

### ISSUE THREAD

**Issue by CaptInsano** [pix/aeon#62]
As per solution to: http://github.com/pix/aeon/issues/closed/#issue/46 ;

A shortcut to file manager was an option for the main menu, that option had a default background image put in by Mindweaver. However in most recent skin version the image is gone and "Files" just has a black background on Main Menu.

**Comment by pix** [comment]
Closed by c59de63bf4bb17a0c1fc83b2b32dafd9cbc6a991: No default background image for "Files" shortcut in Main Menu

I seems to have missed a path while cleanin things up
