### ISSUE TITLE
Adding Trailers - Different Skin Areas Inconsistent

### ISSUE THREAD

**Issue by mark007** [pix/aeon#64]
I think I have found a niggly little bug but unsure if its skin or xbmc related.

I had a movie today which I was playing around with adding / removing trailers as I found better quality ones from different sites.

I had the movie "Quantum Of Solace". I added the <movie name>-trailer.m2ts file, and loaded up xbmc. I see two areas of the skin are then inconsistent. When hovering over the movie in showcase mode, I don't see the "Press UP to see trailer" message. I accept this as I feel I probably need to manually reload the movie data (I wish it was automatic though), HOWEVER, when I go to that movies info screen, the skin suggests I have got a trailer...

See difference in representation of presence of a trailer here.
Indicates no trailer http://img839.imageshack.us/i/1after...ailerfile.jpg/
Indicates trailer http://img80.imageshack.us/i/2trailerappears.jpg/

So my question here is, why are the two areas of the skin inconsistent? Is it a skin problem, or an xbmc relating incorrect information to the skin problem?

After reloading the movie data, both areas of the skin show the indication that a trailer exists.
http://img101.imageshack.us/i/3afterreloadingdata.jpg/

Using latest skin as of 31st of July, with xbmc svn 32375, youtrailer option disabled.

**Comment by pix** [comment]
I thinks you make have activated youtrailer in Aeon settings. YouTrailer is not availaible (yet I thinks) for Dharma, but the code Is still here (And not functional). You should disable YouTrailer in Aeon custom settings for now, and may fill an "Feature Request" while waiting for a Dharma-Compatible youtrailer :-)

Can you confirm ?

**Comment by mark007** [comment]
Yes see my edit to my main post above, youtrailer is disabled when I went to check in settings... so I don't think that is the cause.

You should be able to reproduce by creating a <movie>-trailer.avi for example, for a movie you don't currently have a trailer for. Load xbmc.

In showcase view, you don't see the "Press UP for trailer" but in the information area of that movie, you'll see the "Trailer" button is enabled. I think both should be consistent with eachother. I know its only a small thing that won't bother many but its something I have noticed a few times over the past few days while working on getting high res trailers for some movies..

**Comment by pix** [comment]
>  HOWEVER, when I go to that movies info screen, the skin suggests I have got a trailer...

And what happen when you click this button ? Can you post the xbmc.log log file ?

**Comment by pix** [comment]
Any updates ? Do you have a logfile when you click the trailer button ?

**Comment by mark007** [comment]
Sorry, didn't see reply a few days ago. If I hit the trailer button in info;, the trailer plays perfectly....

Yet the main library window doesn't indicate I have a trailer, and the info dialog does.

Log sent to you on xbmc forums private messages.

**Comment by mark007** [comment]
BTW, just before the log above, I downloaded a trailer for the movie Zodiac, ie Zodiac-trailer.m2ts

**Comment by pix** [comment]
Reproduced :) But now it's time for bed ;)

**Comment by mark007** [comment]
:) You deserve it, keep up the good work on the skin!

**Comment by pix** [comment]
It's because xbmc DialogVideoInfo perform an extra check when this dialog is opened, to see if a trailer is present. It should update the database, right after but there's be a bug which prevent xbmc from doing so ( See http://trac.xbmc.org/ticket/9824 )

I

**Comment by mark007** [comment]
Excellent, thanks for creating the xbmc report.
