### ISSUE TITLE
Showcase Flow in Pictures

### ISSUE THREAD

**Issue by phil65** [pix/aeon#65]
Showcase Flow in Pictures doesn´t work
have to check whether we try to fix it or simply lock it to flat view.

**Comment by pix** [comment]
It seems to work for me ? What doesn't work ?

**Comment by phil65** [comment]
Hmm seems to work here now too. Perhaps it has to do with settings? (dvdcase for example?) must be tested, didn´t work here some days ago.

**Comment by phil65** [comment]
i now had it again once that artists did not scoll properly (-->the same controls for square icons) wasn´t able to reproduce it though

**Comment by phil65** [comment]
fixed in font_rework
