### ISSUE TITLE
Messy cast list on info page

### ISSUE THREAD

**Issue by ghost** [pix/aeon#66]
I don't know if this is a bug but it's close to not working. I think the font used is a bit too big, you have like one pixel between every line and when you read it on a tv it's really hard for your eyes.

It would look much better if you lowered the size of the font by like 1 size or if you put separation lines between each row.

http://img84.imageshack.us/i/screenshot000nj.png/

http://img405.imageshack.us/i/screenshot001wp.png/

**Comment by ghost** [comment]
Or actually dont lower the size of the font, it would look weird compared to the other stuff like director. Just make some more room between each row :)

Feeling like a shit complaining like this but don't take me wrong, the skin is really coming together now, since You fixed the genre fanart things in my opinion :) REALLY NICE!

**Comment by pix** [comment]
Closed by 3267dfd1b8bd401a4a9be13eabffadadc2427e6a: Messy cast list on info page

I've modified linespaceing back to 1 and adjusted some textbox. Tell me
if some label seems misaligned due to this change.
