### ISSUE TITLE
Numeric Sort - Both Ways

### ISSUE THREAD

**Issue by mark007** [pix/aeon#67]
Hi,

I have started to use the movies by year feature alot over the past week or so. This is a feature request to ask that the numeric sort by options be able to sort both from large to small aswell as from small to large.

For example, I have been trying to find some unwatched movies from 2010 in my movie library, but because sort movies by year always sorts from smallest to largest, I need to scroll all of the way to the bottom each time.

So this is a very low priority feature request if you have time to implement an option to choose what way to sort each numeric "sort by" like one might see on an online store, ie high to low or low to high.

**Comment by phil65** [comment]
done (needs some fixing perhaps)
