### ISSUE TITLE
Movies By Year / Others - Irrelevant Options Cleanup

### ISSUE THREAD

**Issue by mark007** [pix/aeon#68]
Hi,

Just trying out some of the ways to view movie / tv show data today, when the down arrow is pressed from "Movies" in the main menu, eg Year / Studios etc.

I notice alot of options in there that have no relevance to the view. I wonder if time permits, could these be navigated through and options and views that arn't relevant be removed. 

One Example: Movies by year, shows options like sort by, wide, info, background that are not clickable or have no function but the user may think they are. See greyish box for example when background is highlighted below.

http://img840.imageshack.us/i/unnecessaryoptions.jpg/

I know this might involve alot of work as there are so many views to analyze...... Thanks!

**Comment by pix** [comment]
Closed by a65a8e3d35f695d2d43489f35d0ae72fc1bc4a56: Movies By Year / Others - Irrelevant Options Cleanup
