### ISSUE TITLE
Text spacing not consistent on main menu

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#7]
[Fav] [Music] [TV series] [Shutdown] [Signout]..............

Spacing between long and short labels are not consistent. Consider changing control type to Image.

**Comment by mindweaver** [comment]
Image? then it won't be able to localize to different languages?

**Comment by kin0kin** [comment]
You are right, gotta find a better solution. Gonna study some string formatting when I have the time.

**Comment by mindweaver** [comment]
I requested dynamic lables that set width by text length but it didn't fly. They said it wasn't possible :( 

EDIT: Dynamic labels seems to have been created and works. But we need the itemlayout and focusedlayout of the wraplist to also be auto. Or else it will not work :/

**Comment by temmi2000** [comment]
nothing we can do about that, changing to images is not an option in my opinion. close this?

**Comment by pix** [comment]
See mindweaver comment it seems it's possible.

**Comment by phil65** [comment]
not possible, only working for grouplists. ---> closed
