### ISSUE TITLE
TV Show Episode - Showcase missing thumbs, missing informations

### ISSUE THREAD

**Issue by mark007** [pix/aeon#70]
Hi,

When I navigate to an episode of a tv show in list view, then switch to showcase view the following effect is seen where no thumbs for episodes show up, and no information on each episode.

http://img825.imageshack.us/img825/5571/listtoshowcase.jpg

There is also two "Thumb" entries
http://i.imgur.com/7wVAx.jpg

Using xbmc 32416, latest aeon65 as of 2nd August

_Edited: Removed xbmc problem_

**Comment by pix** [comment]
Does the thumb still missing ?

**Comment by mark007** [comment]
Since I switched from showcase, to list, and back to showcase, tv show episodes no longer show information such as plot, aired dates, but I can now see the thumbs at least for each episode.

See image below showing missing information, duplicate "THUMB: FANART" entry in the menu on the left, and blank popup when hovering over show info panel. TV Show Episode browsing in showcase seems to be badly broken.

http://img375.imageshack.us/img375/1598/missinginformation.jpg

**Comment by pix** [comment]
Closed by b508778156c530e3835056bd720634d3e5b9119a: TV Show Episode - Showcase missing informations

**Comment by mark007** [comment]
Tyvm, just one slight issue remains, the "THUMB: " entry in the menu still exists twice. Didn't get a chance to check if blank menu appears when hovering on some other items in the menu like http://img375.imageshack.us/img375/1598/missinginformation.jpg. Will check after work .

**Comment by pix** [comment]
Fixed :-)
