### ISSUE TITLE
TV Show Episodes - Year 1601

### ISSUE THREAD

**Issue by mark007** [pix/aeon#71]
Hi, as confluence doesn't show a year field for an individual tv show, I am reporting here instead.

For all of my TV Show Episodes, aeon65 says the year for that episode is 1601.. After checking the nfo's for each episode, created with Ember Media Manager, I see its storing the aired dates as something like <aired>2004-10-13</aired>

**Comment by pix** [comment]
If you see 1601 here: http://i.imgur.com/xGvjD.jpg  then it's probably a scrapper bug.

**Comment by mark007** [comment]
When I press information on any tv show episode, they show the correct year. Its when I highlight the tv show in showcase view, it shows up with year 1601 for all episodes of every tv show I have.... Can you reproduce this?

**Comment by ghost** [comment]
This happens to me to, when I sort in year. But I think it's on the episodes who have blank year.

**Comment by mark007** [comment]
So theres two slight issues here, the strange 1601 year, and should I create a new feature request to have the full date rather than just year used, ie 2000-10-04

All of my tv show episodes contain the full aired date. Would be nice to see the full string in there.

**Comment by ghost** [comment]
I don't think this is a skin issue though, am I wrrong?

**Comment by pix** [comment]
> Its when I highlight the tv show in showcase view, it shows up with year 1601 for 
> all episodes of every tv show I have.... Can you reproduce this?

Err no, when I highlight the show in showcase I get a blank dialog like this: http://i.imgur.com/l7uHL.jpg (I know I should submit a bug report :-) )

Where do you see the year ?

**Comment by mark007** [comment]
When I highlight an episode in aeon65, I get an information box that moves down showing a thumb of that episode, a year....

**Comment by pix** [comment]
In this view ? This is empty for me: http://i.imgur.com/hHp9c.jpg

**Comment by mark007** [comment]
Strange.. I always had information about my tv episodes, showing a piece of text describing the episode etc.

I actually can't get into tv show episodes correctly now due to the following http://github.com/pix/aeon/issues#issue/70

The crash is of course xbmc related, but I don't know if the switching from list back to showcase making things go like this is xbmc, I thought it might be aeon related.

**Comment by mark007** [comment]
Hi, I can't reproduce with latest version as of 11 Aug. I even manually removed the air date and reloaded the info for one episide and aeon65 correctly says "INFO NOT AVAILABLE" so I think this is fixed...

**Comment by pix** [comment]
Ok, closing.
