### ISSUE TITLE
Videos Section Background suddenly appears black...

### ISSUE THREAD

**Issue by Shinu** [pix/aeon#76]
the background of my video section suddenly appears black. i can't exactly recall, but i believe the background used to be the multiplex curtains. don't kno why it's not displaying. is there a way to fix this or have the mainscreen backdrops display when in the videos section? here's a few screenshots to show the issue....

http://img541.imageshack.us/img541/2774/842010105025am.jpg

http://img16.imageshack.us/img16/2537/84201021406pm.jpg

**Comment by pix** [comment]
Closed by f110b7126917aa87fb0c5f7cba92e75950ce884c: Videos Section Background suddenly appears black.
