### ISSUE TITLE
Info Screen - Show More Meta Data

### ISSUE THREAD

**Issue by mark007** [pix/aeon#79]
Hi, This is a feature request to have the info screen updated with regard to metadata.

I have alot of meta data for most movies, eg "The Dark Knight" library view shows lots of lovely meta data, like truehd, warnerbros symbol...

http://img265.imageshack.us/i/libraryf.jpg/

The info screen contains lots of room at the bottom for meta data like this but doesn't show any in this case except for vc-1. Can this be updated to show maybe audio format and other relevant metadata.. just instead of the three empty boxes seen currently...

http://img806.imageshack.us/i/truehd.jpg/

While playing around with the meta data for this movie, i notice a little white blob on the left hand side of the vc-1 png file highlighted with red circle in image above. If this isn't by design, I have uploaded the vc-1.png file without this blob http://img202.imageshack.us/img202/8577/vc1d.png

And finally, media managers that I personally use like Ember Media Manager, use the string "truehd", rather than "dolbytruehd", which aeon65 doesn't seem to understand as of yet. Can dolbytruehd.png be duplicated in truehd.png for others that may also have metadata containing this "truehd" string.... I'm not aware if any of this is standardised or not....

Thanks as always!

**Comment by mark007** [comment]
Another meta string the skin doesn't seem to load up currently is dtsma. For dtsma I get a dts5.1 image instead of the lovely dtsma image. Also not sure if source is supposed to be shown eg bluray or dvd etc?

**Comment by temmi2000** [comment]
can be closed now i think, only dtsma is missing in dialogvideoinfo

**Comment by mark007** [comment]
I think its looking great, thanks guys. Yeah just dtsma seems to be missing..

**Comment by mark007** [comment]
I see a new commit from yourself temmi2000 http://github.com/pix/aeon/commit/0429cfb23cffb02d7f4f1d4464cdcdb82a172786 but I still see dts51 image rather than dtsma. I assume this is because currently the skin loads the images in a certain defined order in the xml file?

My nfo for this particular movie I'm testing with has various stream info like the following, with the primary one being dtsma of course. The others are just dca and dd audio tracks I might never use, but are all scraped into the nfo by ember media manager. Its always the number 1 audio stream that I think should appear on the skins gui if possible.... in this case dtsma.

<audio>
        <channels>6</channels>
        <codec>dtsma</codec>
      </audio>
      <audio>
        <channels>6</channels>
        <codec>dca</codec>
      </audio>
      <audio>
        <channels>6</channels>
        <codec>dca</codec>
      </audio>
      <audio>
        <channels>6</channels>
        <codec>dca</codec>
      </audio>
      <audio>
        <channels>6</channels>
        <codec>ac3</codec>
      </audio>

So I'm not sure if its possible to have the aeon skin load images in order they are found in the xbmc xb, or are they sorted at all.

**Comment by temmi2000** [comment]
does it work when you remove the other sound streams from the xml? (you have to reload the info then of course)

**Comment by mark007** [comment]
Yes it works perfectly with the others removed. When this substring function is called in the Includes_MediaFlags.xml file, what language is it, I thought python....

I was going to try replacing all references to ListItem.AudioCodec with something like ListItem.AudioCodec[0] but of course I'm not sure what language it is. If xbmc stores the imported audiocodecs and audio channels in the order they are in the nfo then theres hope.... I'd love to have a stab at sorting this out...

Would love to start making contributions.. but only of course if thats ok with you guys. You can check my first attempts at a commit to make sure all looks ok.

**Comment by temmi2000** [comment]
Of course, everyone is welcome to help out.
but in this case i think there´s nothing a skinner can do.
as far as i know xbmc should take the details from the first audio stream...
you would have  to contact the xbmc developers about this.

**Comment by mark007** [comment]
OK will do, I thought it was an array of strings... instead of just one string I assume. I'll make an xbmc trac report.

http://trac.xbmc.org/ticket/9925
