### ISSUE TITLE
Auto Timer - Wrong Language?

### ISSUE THREAD

**Issue by mark007** [pix/aeon#80]
Hi, i notice the text when selecting the number of seconds for the auto timer isn't in English....

ie Sekunde vs Second, SEKUNDEN vs Seconds

http://img97.imageshack.us/img97/6865/screenshot009ll.jpg

Using aeon65 from 9th Aug.

**Comment by pix** [comment]
Closed by 716f1c428e6316b23b3f264a79af99338376a698: Auto Timer - Wrong Language?
