### ISSUE TITLE
Request: Bluray, DVD Cases

### ISSUE THREAD

**Issue by butchabay** [pix/aeon#82]
Here is my request:
What abaout Bluray, DVD Cases ? I've seen it in Alska's BIG MOD. See here:

http://img90.imageshack.us/i/bigalaska1.jpg/

That would be nice. What do you think ?

**Comment by pix** [comment]
I'm not a big fan of this. I'm not sure it would fit Aeon style very well. What do you think phil ?

**Comment by kraaa** [comment]
+1 from me
http://img196.imageshack.us/img196/640/wallstreamwithcases.jpg

would love it ;D

**Comment by pix** [comment]
My two cents:

Like I said, this imho would not fit into Aeon style. You could prove me wrong with a mockup, butt I will not integrate Bluray/DVDcase like the one in the screenshot. If someone would come up with Aeonish artwork for ths maybe I could, but not these DVD Cases, they doesn't fit.

**Comment by butchabay** [comment]
Ok, just see this Video. It's AEON Showmix ... You really think they doesn't fit ? :)
http://www.youtube.com/user/iMeAgainstTheWorldi#p/u/16/wsPhCpmqFE4
Thanx anyway for all your work.

**Comment by phil65** [comment]
hmmm i like it more than the dvdcases which are included now.

**Comment by pix** [comment]
Personally, I really do not like this; I Like current Translucent DVD cases, There's imho a lot of room for improveemnts elswhere in the skin, before spending time on this.

**Comment by Bat3man** [comment]
Me no likey... Have to agree with Pix: there are a lot of things that can be improved, and this doesn't fit... Just my 2 cents...

**Comment by butchabay** [comment]
This was just a request, it's not a problem for me.
So let's forget it ... thanx anyway for all your work on this skin. 
Cheers

**Comment by phil65** [comment]
then we´ll close it for now, I don´t need this either.
