### ISSUE TITLE
"Info Unavailable" in Music Multiplex

### ISSUE THREAD

**Issue by ghost** [pix/aeon#83]
When artists don't have fanart only the icon shows which is nice but it should also show the artist info where it now says "Info Unavailable".

http://img210.imageshack.us/img210/7933/screenshot005f.png

I have seen this in Aeon Hitched and it worked out really nice.

You can see in this video how it should be, in the beginning when he selects music.
http://www.youtube.com/watch?v=HuDs0HV0Pls

As you see it also shows info when there is a fanart but horizontally. Hope you can make this work again and look as it dit in the original Aeon Hitched.

**Comment by temmi2000** [comment]
should be fixed now
