### ISSUE TITLE
Change Scraper in Music Library Disabled

### ISSUE THREAD

**Issue by jeneral** [pix/aeon#84]
Using the context menu on an artist and selecting 'Change Scraper'. A dialog window opens up but no options are selectable. I am using Aeon65 in Showcase view.

**Comment by phil65** [comment]
please try again, should be fixed now

**Comment by pix** [comment]
phil65: When you commit you can put for example:

"Closes #84: Change Scraper in Music Library Disabled"

And it will automatically close the issue.

**Comment by jeneral** [comment]
Thanks for fixing this. One suggestion: The current scraper should be highlighted (or some other button). Right now, after after selecting change scraper, nothing is highlighted until a cursor key is pressed on the remote.
