### ISSUE TITLE
Backdrops in showcase view for music videos missing

### ISSUE THREAD

**Issue by hbooo** [pix/aeon#85]
In showcase view there is no backdrops in music video. There is no options to activate or not backdrops in options and sub menu of "show info panel" isn't visible.

http://img706.imageshack.us/img706/7578/sanstitreinf.png

There's no background in TV Shows genre too

**Comment by pix** [comment]
Closed by 658774a0ee2bedec079fc15254a367bb3112d97d: Backdrops in showcase view for music videos missing
