### ISSUE TITLE
Aeon65 tries to activate an invalid view number (view number+1 instead of view number)

### ISSUE THREAD

**Issue by pix** [pix/aeon#86]
http://trac.xbmc.org/ticket/9807#comment:9

It's most likely the <visible> conditions on all the views that's causing it. Unless there is actually a case where the skinner can identify that XBMC is doing something wrong, there's not a lot I can do. Open a new ticket if that is the case.

**Comment by temmi2000** [comment]
anyone havin those crashes? no problems here..

**Comment by pix** [comment]
The crash isn't present since it has benn fixed in xbmc, It might still be a problem. I'm closing this now, I weird behaviours still shows up i'll reopen this
