### ISSUE TITLE
Sort By Episodes - Doesn't work in tv shows

### ISSUE THREAD

**Issue by mark007** [pix/aeon#87]
Hi,

Using latest aeon65 from aug 14th. Sorting in tv shows library mode by episode doesn't work. When I change from sort by name to sort by episodes there is no change, even though some tv shows have say 15 episodes, some have hundreds, but they arn't getting sorted by number of episodes.

**Comment by phil65** [comment]
hmmm should be an xbmc problem...
did you also try other skins?

**Comment by mark007** [comment]
You're right, it happens with confluence, sorry about that. Will close now.
