### ISSUE TITLE
Backdrop images are shown behind the fanart in Movies Multiplex view

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#88]
## Relevant Settings:

Section: Movies
View: Multiplex
Show Info Panel: Auto
Background: Fanart
Settings / Main Menu / Backdrops / Movies is set to a Slideshow Folder
## Description:

The backdrop images keeps cycling behind the fanart. This is briefly seen as the fanart fades in and out each time you navigate left or right. More easily seen if you press and hold left or right. It would look much nicer if the backdrop images were disabled when you have the background set to Fanart.

**Comment by pix** [comment]
Closed by 869af78cf56b0b3b09d22a2b7c50eb4b549506ec: Backdrop images are shown behind the fanart in Movies Multiplex view
