### ISSUE TITLE
Showcase View in Music - Fanart Window Aspect Ratio

### ISSUE THREAD

**Issue by jeneral** [pix/aeon#89]
I notice that when using showcase view in my music library, the aspect ratio of the fanart window varies from artist to album view. Here is the artist view:

http://a.imageshack.us/img186/7803/screenshot000y.jpg

After selecting the above artist, the aspect ratio of the image changes when viewing the albums (notice his hair now touches the top edge of the frame):

http://a.imageshack.us/img413/7320/screenshot001ax.jpg

It would also be nice to find a use for the 'Unwatched' field when viewing albums in Showcase view (second image).  Maybe Moods, Themes, Release Date, Time, etc... or some other unused field.

**Comment by pix** [comment]
Closed by 1c9550011596110309ae5d9071c81ed92037fa34: Showcase View in Music - Fanart Window Aspect Ratio

**Comment by jeneral** [comment]
Looks great pix. Thank you for these changes!
