### ISSUE TITLE
guisettings.xml not sticking on first install.

### ISSUE THREAD

**Issue by kin0kin** [pix/aeon#9]
*Reproduced by first installing XBMC then launch XBMC and set the settings for the first time. Exit XBMC and relaunch XBMC, some settings would get reset.
(animate background, for example, gets turned on after you go back into XBMC since initial setting)

**Comment by mindweaver** [comment]
Is this really a skin issue?

**Comment by PBoD** [comment]
I can confirm this, at least to the point of animate backgrounds being turned back on. I didn't notice any other changes to the settings though.

**Comment by sergiocos** [comment]
Animated backdrops on main menu (ON)
Global RSS (ON)
Recently Added (ON)... no matter what you set on first run, they wil behave like this on second run. After modifying these settings, the skin will behave normally, guisettings will kick in and do his part.

**Comment by pix** [comment]
Thanks for the additionals information, i'll try to look at the differences beetween theses settings an the others when i'll have some time.

**Comment by phil65** [comment]
that´s correct, it´s because we set some standard settings when Aeon65 starts up from the beginning for the first time (-->startup.xml)
i think we could adjust it so that it also sets these settings when changing the skin. will look at it.

**Comment by phil65** [comment]
hmm seems impossible --> closed
