### ISSUE TITLE
TV Show Fanart Disappears After Reload

### ISSUE THREAD

**Issue by mark007** [pix/aeon#90]
For tv shows, I use a folder.jpg file for the poster. I have two issues, one may be xbmc and one may be aeon related. Hopefully someone can help me figure our if xbmc is at fault for one or both.

After reloading data for a tv show, the library mode shows this new image perfectly, but the information dialog for that tv show shows an old seemingly cached version of that image.... This is probably xbmc related but just incase you know if it can be resolved from aeons point of view I mention it here. Hopefully you can produce also. See image below showing an old squiggled version of a tv show poster (squiggle highlighted in red). See here -> http://img412.imageshack.us/i/screenshot001cu.jpg/

So today I tried with the latest xbmc and aeon as of aug 16th, and reloaded the data for the tv show (selected no to get data for all tv shows, and selected no to get data from the internet). After the reload, the old cached version still shows up in the information dialog, but when I then back up to the library view, the fanart for the tv show seems to disappear from the little info box thats above the poster. See here -> http://img203.imageshack.us/i/screenshot002ijf.jpg/

I assume the second one is a slight aeon issue, because the fanart correctly shows up in the background as can be seen in the screenshot above also. I havn't tested other areas of the skin to see if this slight missing fanart on reload issue also appears...

Moving left and then back right to the tv show fixes the missing fanart issue, so its only a minor thing but worth reporting.

**Comment by pix** [comment]
The second one is as far as I know probably an xbmc issue (I can reproduce the same issue with the lowlist view for example, I didn't tried Confluence but i suspect the same behaviour)

I can't reproduce the first issue, have you tried with a more recent XBMC build ?

**Comment by mark007** [comment]
Hi pix. A similar effect to the second issue is seen with confluence, will post at xbmc trac, thanks.

For the first issue. With latest xbmc svn as of today, and after the fix for this report http://github.com/pix/aeon/issues/issue/93 now my folder.jpg gets shown in the info dialog but two issues still exist.

1) As the folder.jpg is blended in, I can now see the old, I assume xbmc cached version of my old postered from weeks ago... This poster no longer exists so I'll post over at xbmc trac. xbmc seems to be holding onto a cached version of it somehow.

See here, the old poster with the black squiggle I created months ago and have since deleted from my machine still shows up before folder.jpg is blended in.

http://img189.imageshack.us/i/screenshot006vn.jpg/

2) The second issue, now that folder.jpg shows up correctly, it also seems to be a scaled down (resolution wise) version of the one from disk. Is this under aeon control? I can get around the scaling for info dialog for movies, by creating a movie.tbn which preserves the original quality, but have no such workaround for information dialog for tv shows.

See here info showing fanart.jpg (looks very blurry)
http://img836.imageshack.us/i/screenshot007t.jpg/

compared to the fanart.jpg file original from my TV Show folder.

http://img832.imageshack.us/i/folderoo.jpg/

Let me know if aeon isn't under control of any of this or if is of course..

I'll begin writing a trac report for xbmc.

**Comment by mark007** [comment]
Still discussing this and posters on the xbmc forums...
http://forum.xbmc.org/showthread.php?p=588381#post588381

One issue I think can be improved on aeons side anyways is for the info dialog for tv shows to do something similar to what is done for movies, ie show the unedited version of the poster...

For movies if I use movie.tbn file format, I see a pure unscaled / uncached version of the poster. Can a similar feature be implemented for tv shows, because I'd absolutely love to have a way to display high res posters directly from disk in tv shows like is done with movies.

I have tried the following formats, but aeon65 seems to only show the cached version.. and I'm not sure what else it draws on top of that.(probably doing things by the book)

poster.tbn
folder.jpg
poster.jpg
Dexter.jpg
Dexter.tbn
movie.tbn

Shall I create a seperate request feature request to have aeon65 be able to load directly these files from disk in the info dialog like is currently done with movie.tbn for movies... or is this not possible to do? If aeon could load all of these files directly from disk I am sure everyone would see an immediate improvement in quality in their info dialogs...

**Comment by mark007** [comment]
xbmc report for fanart disappearing on reload http://trac.xbmc.org/ticket/9926

**Comment by mark007** [comment]
All issues fixed on trac now after bug reports there, so I'll close off this now but just wondering, is it appropriate to make a new feature request on here to allow the info dialog to read a file directly from disk on the info dialog for tv shows, instead of showing the scaled down poster... just as movie.tbn is shown from disk in the info dialog for movies.

**Comment by pix** [comment]
You could, but there's imho some more important issue to fix, and manpower is limited :)
