### ISSUE TITLE
No texture for Video OSD Menu

### ISSUE THREAD

**Issue by mindweaver** [pix/aeon#91]
As the topic says, the background texture for Video OSD menu as gone missing.

**Comment by temmi2000** [comment]
i changed it to a half transparent black gradient background (never really liked the Video OSD)
i should make the background less transparent perhaps,
if noone likes this I could also revert it.

**Comment by pix** [comment]
I'm not a huge fan of this backgroundless OSD. The osd feels strange now (Like it has not texture :)). My thoughts are that's the same idea that: http://forum.xbmc.org/showthread.php?t=79126 .  It's great, but it's not _Aeonish_

So, my vote goes for revert :)

> Edit: Didn't noticed at first your answer.
> This has been introduced by commit 7482177327fddd0010f7b65196a0f9e6c7b710da.
> I don't know why phil changed this.

**Comment by sergiocos** [comment]
let's try 'less transparent' first... Feels strange for me too...

**Comment by temmi2000** [comment]
second attempt, opinions please

**Comment by sergiocos** [comment]
looks perfect now, for me at least...

**Comment by mindweaver** [comment]
It just a black mess now :( and the lines from the sides just doesn't match Aeon. I like the original textures more.

**Comment by mindweaver** [comment]
your first fade attempt was pretty ok when I knew there was actually a fade :) just the PAUSE tab didn't fit and it wasn't consistent on pause, info and skip stuff. only M menu.

**Comment by pix** [comment]
This is not consistent with MusicOSD too, which shows the old texture. I agree with mindweaver, The pause label does not fit whit the black shadow.

**Comment by temmi2000** [comment]
reverted to the old style and added smoke effect. closed.
