### ISSUE TITLE
Info For TV Season - Incorrect Poster Shown

### ISSUE THREAD

**Issue by mark007** [pix/aeon#93]
Hi,

I have posters for tv shows, for each tv show season, and when viewing the info for a tv show season, I can see the poster for that season on the left hand side for maybe 1/4 of a second. Then an animation begins where the poster for the tv show itself fades in and hides the season poster...

See animation starting here (with season poster behind about to be covered).
http://img823.imageshack.us/i/screenshot003r.jpg/

Then a second later, its completely covered.
http://img801.imageshack.us/i/screenshot004p.jpg/

Using latest aeon as of 18/08 and xbmc also.

**Comment by pix** [comment]
Moved poster.jpg and folder.jpg before Xbmc own thumbs.
Moved as it conflicts with seasons thumbs.

Closed by 74030b5eed84d8c2d6e98afc082e6375a409dbf6: Info For TV Season - Incorrect Poster Shown

**Comment by mark007** [comment]
tyvm!
