### ISSUE TITLE
Smoke effect not covering the whole screen

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#95]
This might be by design but to keep the subsections consistent with the main menu (which is the only place where the smoke effect covers the whole screen) I think the whole background should be covered.

**Comment by temmi2000** [comment]
made by design..
what do you mean with subsections? the library views?

**Comment by sialivi** [comment]
Yes. So when navigating from the main menu (with smoke effect on the whole screen) to the movies section with multiplex (where the smoke effect only covers the info panel) it feels slightly inconsistant. Especially when the info panel is hidden at first, which means there's no smoke effect at all until the info panel pops up.

**Comment by pix** [comment]
It feels better as it is now to me.

**Comment by temmi2000** [comment]
i also like it the way it is. will stay this way for now.
