### ISSUE TITLE
Darkening the Multiplex background fanart

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#96]
When using Multiplex with background set to fanart, I think it would look nice if the background was faded to darker when the info panel is shown to make the panel "pop" a bit more and draw the attention away from the background to the foreground.

**Comment by temmi2000** [comment]
thx for the idea, added for multiplex

**Comment by sialivi** [comment]
Excellent, looks great. Maybe speed up the fade a bit?

**Comment by sialivi** [comment]
There's a small bug. The height of DarkOverlayCommon isn't big enough so a small strip of the background doesn't darken.

**Comment by temmi2000** [comment]
at the top or at the bottom?
my 16:10 resolution could cause such things..
i made it a bit faster now.

**Comment by sialivi** [comment]
At the bottom, this is on a 16:9 display

**Comment by sialivi** [comment]
Sorry to be a pain in the ass, the speed is much better now, but I think it will be even better if it matches the speed of the Info Panel animation

**Comment by temmi2000** [comment]
try again, i think it was because of the showcase extended info option.

**Comment by sialivi** [comment]
The whole background darkens now, perfect
Speed looks unchanged

**Comment by temmi2000** [comment]
after some trying i have to say you´re right...
i set it to 600 now, that should be fast enough.

**Comment by sialivi** [comment]
Perfect speed :)
...but there's always a but isn't there ;)
The first time it fades when entering the movie library it fades alot slower than the fades when you navigate from movie to movie, so I'm guessing there's another value that also need to be set to 600

**Comment by sialivi** [comment]
...line 168 and 718 in Viewtype_Multiplex if I'm not mistaken

**Comment by temmi2000** [comment]
thx, fixed

**Comment by pix** [comment]
I'm closing this, cause i seems it's fixed.
