### ISSUE TITLE
Random fanart for movies which has no fanart

### ISSUE THREAD

**Issue by sialivi** [pix/aeon#97]
## Relevant Settings:
- Multiplex with background set to fanart.
- Movies backdrops are set to a slideshow folder which contains the fanart for all movies I have in my library. This is because I want a slideshow of all my movies on the main menu when Movies is selected.
## Problem:

The result is that when navigating the movie library, I get random movie fanart for all movies which has no assigned fanart. This has confused my weekly movienight guests on more than one occasion.
## Suggestion:

I would prefer if the red curtains, which shows when you set background to "backdrop" or no image at all, to show for movies with no fanart.

**Comment by pix** [comment]
How can we deal with this wihout adding too much complexity ? I have a custom set of background (Not movie related, And I would not want to have a red curtain when I have no fanart for a particular movie)

Any idea ?

**Comment by sialivi** [comment]
Hard for me to determine complexity since I know next to nothing about xbmc skins. Would introducing a new aeon skin setting for selecting "default movie fanart" be out of the question? That way it shouldn't effect the library views complexity very much?

**Comment by pix** [comment]
I'm not very fond of adding another skin setting. I personnaly found Aeon65 to have too much skin settings (It's a PITA to read some utterly complex boolean expressions in some areas of the skin)

It should be feasible, but I'm not particularly fond of it.

**Comment by temmi2000** [comment]
Does the fallback option not work?

**Comment by sialivi** [comment]
Fallback option?

**Comment by temmi2000** [comment]
yes, fallback option (now in advanced-->fanart)

**Comment by sialivi** [comment]
Excellent. :)

Can you please change .jpg to .jpg|.png in Customisation.xml line 322 and 330?

Also, not sure if this is by design or not, but only the backdrop fanart use the fallback image. The fanart on the info panel does not.

**Comment by pix** [comment]
Closing as it seems it's fixed
