### ISSUE TITLE
No info for music files in lowlist (tracks level) when High List selected

### ISSUE THREAD

**Issue by sergiocos** [pix/aeon#98]
Tags from comment field are showed in COMMENT: ... field. If Low List is set to High(er) list, the info dissapears. However, when i play some file, the biograpgy for that artist is showed (only for that file). I can ahow you with some scrshots, when i get home, if needed.

**Comment by pix** [comment]
Closed by 030ff049041d585016a2ccf8e9a071fe45c03b29: No info for music files in lowlist (tracks level) when High List selected

**Comment by sergiocos** [comment]
Half closed :) Now the info is showed ok, but still the biography is triggered at play and showed OVER the info (sometimes i noticed a switch between comment/description to biography/artist, sometimes both are showed)
http://img710.imageshack.us/img710/7605/screenshot003qd.png
